-- Sample data for the dev harness and screenshots (never run by the Chest):
-- Atelier Martin's forms. Generated; ids of lab/chest-dev/cast.mjs.

insert into forms (id, slug, owner, status, audience, anonymous, once, tell_team, layout, accent, draft, revision, version, closes_at, max_answers, thanks_title, thanks_body, redirect_url, send_copy, retention_months, answer_count, bell_at, created_at, updated_at, published_at, closed_at)
overriding system value values (1, 'k7m2fq9d', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 'published', 'public', false, true, false, 'steps', 'berry', '{"title":"How did we do?","intro":"Two minutes of your time help our workshop a lot. Thank you!","pages":[{"id":"p7xxxxxx","title":"","questions":[{"id":"q1xxxxxx","kind":"rating","title":"How would you rate our service?","help":"","required":true,"steps":5},{"id":"q2xxxxxx","kind":"scale","title":"How likely are you to recommend Atelier Martin to a friend or colleague?","help":"","required":true,"from":0,"to":10,"left":"Not likely","right":"Very likely"}],"jumps":[{"when":{"question":"q2xxxxxx","op":"lt","value":7},"to":"p9xxxxxx"}]},{"id":"p8xxxxxx","title":"","questions":[{"id":"q3xxxxxx","kind":"long","title":"What did you like most?","help":"","required":false}],"jumps":[{"when":{"question":"q2xxxxxx","op":"answered"},"to":"paxxxxxx"}]},{"id":"p9xxxxxx","title":"","questions":[{"id":"q4xxxxxx","kind":"long","title":"What should we do better?","help":"","required":false}],"jumps":[]},{"id":"paxxxxxx","title":"","questions":[{"id":"q5xxxxxx","kind":"yesno","title":"May we contact you about your answers?","help":"","required":false},{"id":"q6xxxxxx","kind":"email","title":"Your email address","help":"","required":true,"showIf":{"question":"q5xxxxxx","op":"is","value":true}}],"jumps":[]}],"language":"en","alt":{"language":"fr","texts":{"title":"Comment nous sommes-nous débrouillés ?","intro":"Deux minutes de votre temps aident beaucoup notre atelier. Merci !","q1xxxxxx":"Comment notez-vous notre service ?","q2xxxxxx":"Recommanderiez-vous Atelier Martin à un ami ou un collègue ?","q2xxxxxx.left":"Peu probable","q2xxxxxx.right":"Très probable","q3xxxxxx":"Qu’avez-vous le plus apprécié ?","q4xxxxxx":"Que devrions-nous mieux faire ?","q5xxxxxx":"Pouvons-nous vous recontacter au sujet de vos réponses ?","q6xxxxxx":"Votre adresse e-mail"}}}'::jsonb, 3, 1, null, null, 'Thank you so much!', 'Your words go straight to the workshop team.', null, false, 12, 27, now() - interval '2 hours', now() - interval '40 days', now() - interval '1 days', now() - interval '39 days', null);
insert into versions (form_id, version, definition, published_at) values (1, 1, '{"title":"How did we do?","intro":"Two minutes of your time help our workshop a lot. Thank you!","pages":[{"id":"p7xxxxxx","title":"","questions":[{"id":"q1xxxxxx","kind":"rating","title":"How would you rate our service?","help":"","required":true,"steps":5},{"id":"q2xxxxxx","kind":"scale","title":"How likely are you to recommend Atelier Martin to a friend or colleague?","help":"","required":true,"from":0,"to":10,"left":"Not likely","right":"Very likely"}],"jumps":[{"when":{"question":"q2xxxxxx","op":"lt","value":7},"to":"p9xxxxxx"}]},{"id":"p8xxxxxx","title":"","questions":[{"id":"q3xxxxxx","kind":"long","title":"What did you like most?","help":"","required":false}],"jumps":[{"when":{"question":"q2xxxxxx","op":"answered"},"to":"paxxxxxx"}]},{"id":"p9xxxxxx","title":"","questions":[{"id":"q4xxxxxx","kind":"long","title":"What should we do better?","help":"","required":false}],"jumps":[]},{"id":"paxxxxxx","title":"","questions":[{"id":"q5xxxxxx","kind":"yesno","title":"May we contact you about your answers?","help":"","required":false},{"id":"q6xxxxxx","kind":"email","title":"Your email address","help":"","required":true,"showIf":{"question":"q5xxxxxx","op":"is","value":true}}],"jumps":[]}],"language":"en","alt":{"language":"fr","texts":{"title":"Comment nous sommes-nous débrouillés ?","intro":"Deux minutes de votre temps aident beaucoup notre atelier. Merci !","q1xxxxxx":"Comment notez-vous notre service ?","q2xxxxxx":"Recommanderiez-vous Atelier Martin à un ami ou un collègue ?","q2xxxxxx.left":"Peu probable","q2xxxxxx.right":"Très probable","q3xxxxxx":"Qu’avez-vous le plus apprécié ?","q4xxxxxx":"Que devrions-nous mieux faire ?","q5xxxxxx":"Pouvons-nous vous recontacter au sujet de vos réponses ?","q6xxxxxx":"Votre adresse e-mail"}}}'::jsonb, now() - interval '39 days');
insert into access (form_id, member, level) values (1, 'mbr_camilleaaaaaaaaaaaaaaaaaaa', 'viewer');
insert into access (form_id, member, level) values (1, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', 'viewer');
insert into watchers (form_id, member, unseen) values (1, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 3);
insert into watchers (form_id, member, unseen) values (1, 'mbr_camilleaaaaaaaaaaaaaaaaaaa', 0);
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000001', 1, 1, null, null, '{"q1xxxxxx":5,"q2xxxxxx":10,"q3xxxxxx":"Delivery was on time and the team was lovely.","q5xxxxxx":false}'::jsonb, now() - interval '467 minutes', date_trunc('month', now() - interval '467 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000002', 1, 1, null, null, '{"q1xxxxxx":5,"q2xxxxxx":9,"q3xxxxxx":"Beautiful work, my kitchen looks new.","q5xxxxxx":false}'::jsonb, now() - interval '495 minutes', date_trunc('month', now() - interval '495 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000003', 1, 1, null, null, '{"q1xxxxxx":5,"q2xxxxxx":10,"q5xxxxxx":false}'::jsonb, now() - interval '674 minutes', date_trunc('month', now() - interval '674 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000004', 1, 1, null, 'pierre.m3@example.com', '{"q1xxxxxx":5,"q2xxxxxx":10,"q3xxxxxx":"Clear quote, no surprises.","q5xxxxxx":true,"q6xxxxxx":"pierre.m3@example.com"}'::jsonb, now() - interval '598 minutes', date_trunc('month', now() - interval '598 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000005', 1, 1, null, 'anna.k4@example.com', '{"q1xxxxxx":2,"q2xxxxxx":3,"q4xxxxxx":"The invoice had a typo in my name.","q5xxxxxx":true,"q6xxxxxx":"anna.k4@example.com"}'::jsonb, now() - interval '1457 minutes', date_trunc('month', now() - interval '1457 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000006', 1, 1, null, null, '{"q1xxxxxx":5,"q2xxxxxx":9,"q3xxxxxx":"Quick answers by phone.","q5xxxxxx":false}'::jsonb, now() - interval '1496 minutes', date_trunc('month', now() - interval '1496 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000007', 1, 1, null, 'anna.k6@example.com', '{"q1xxxxxx":4,"q2xxxxxx":8,"q5xxxxxx":true,"q6xxxxxx":"anna.k6@example.com"}'::jsonb, now() - interval '2447 minutes', date_trunc('month', now() - interval '2447 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000008', 1, 1, null, null, '{"q1xxxxxx":5,"q2xxxxxx":10,"q5xxxxxx":false}'::jsonb, now() - interval '3030 minutes', date_trunc('month', now() - interval '3030 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000009', 1, 1, null, null, '{"q1xxxxxx":5,"q2xxxxxx":9,"q3xxxxxx":"The finish on the oak table is perfect.","q5xxxxxx":false}'::jsonb, now() - interval '3756 minutes', date_trunc('month', now() - interval '3756 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000a', 1, 1, null, null, '{"q1xxxxxx":2,"q2xxxxxx":3,"q4xxxxxx":"I waited two weeks for the quote.","q5xxxxxx":false}'::jsonb, now() - interval '4728 minutes', date_trunc('month', now() - interval '4728 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000b', 1, 1, null, null, '{"q1xxxxxx":5,"q2xxxxxx":9,"q3xxxxxx":"Delivery was on time and the team was lovely.","q5xxxxxx":false}'::jsonb, now() - interval '5898 minutes', date_trunc('month', now() - interval '5898 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000c', 1, 1, null, 'anna.k11@example.com', '{"q1xxxxxx":5,"q2xxxxxx":9,"q3xxxxxx":"Quick answers by phone.","q5xxxxxx":true,"q6xxxxxx":"anna.k11@example.com"}'::jsonb, now() - interval '6994 minutes', date_trunc('month', now() - interval '6994 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000d', 1, 1, null, null, '{"q1xxxxxx":3,"q2xxxxxx":6,"q4xxxxxx":"The invoice had a typo in my name.","q5xxxxxx":false}'::jsonb, now() - interval '8374 minutes', date_trunc('month', now() - interval '8374 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000e', 1, 1, null, null, '{"q1xxxxxx":4,"q2xxxxxx":7,"q3xxxxxx":"Delivery was on time and the team was lovely.","q5xxxxxx":false}'::jsonb, now() - interval '9801 minutes', date_trunc('month', now() - interval '9801 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000f', 1, 1, null, null, '{"q1xxxxxx":5,"q2xxxxxx":10,"q3xxxxxx":"The finish on the oak table is perfect.","q5xxxxxx":false}'::jsonb, now() - interval '10902 minutes', date_trunc('month', now() - interval '10902 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000g', 1, 1, null, 'claire.fontaine15@example.com', '{"q1xxxxxx":2,"q2xxxxxx":3,"q4xxxxxx":"The delivery slot was given late.","q5xxxxxx":true,"q6xxxxxx":"claire.fontaine15@example.com"}'::jsonb, now() - interval '12679 minutes', date_trunc('month', now() - interval '12679 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000h', 1, 1, null, 'sophie.l16@example.com', '{"q1xxxxxx":5,"q2xxxxxx":10,"q3xxxxxx":"Quick answers by phone.","q5xxxxxx":true,"q6xxxxxx":"sophie.l16@example.com"}'::jsonb, now() - interval '14654 minutes', date_trunc('month', now() - interval '14654 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000i', 1, 1, null, null, '{"q1xxxxxx":5,"q2xxxxxx":9,"q5xxxxxx":false}'::jsonb, now() - interval '15970 minutes', date_trunc('month', now() - interval '15970 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000j', 1, 1, null, 'j.smith18@example.com', '{"q1xxxxxx":3,"q2xxxxxx":6,"q4xxxxxx":"The delivery slot was given late.","q5xxxxxx":true,"q6xxxxxx":"j.smith18@example.com"}'::jsonb, now() - interval '18262 minutes', date_trunc('month', now() - interval '18262 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000k', 1, 1, null, null, '{"q1xxxxxx":5,"q2xxxxxx":9,"q5xxxxxx":false}'::jsonb, now() - interval '20421 minutes', date_trunc('month', now() - interval '20421 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000l', 1, 1, null, 'anna.k20@example.com', '{"q1xxxxxx":4,"q2xxxxxx":8,"q5xxxxxx":true,"q6xxxxxx":"anna.k20@example.com"}'::jsonb, now() - interval '22583 minutes', date_trunc('month', now() - interval '22583 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000m', 1, 1, null, 'anna.k21@example.com', '{"q1xxxxxx":5,"q2xxxxxx":9,"q5xxxxxx":true,"q6xxxxxx":"anna.k21@example.com"}'::jsonb, now() - interval '24692 minutes', date_trunc('month', now() - interval '24692 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000n', 1, 1, null, null, '{"q1xxxxxx":5,"q2xxxxxx":9,"q5xxxxxx":false}'::jsonb, now() - interval '26681 minutes', date_trunc('month', now() - interval '26681 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000o', 1, 1, null, null, '{"q1xxxxxx":3,"q2xxxxxx":5,"q4xxxxxx":"The invoice had a typo in my name.","q5xxxxxx":false}'::jsonb, now() - interval '29144 minutes', date_trunc('month', now() - interval '29144 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000p', 1, 1, null, 'sophie.l24@example.com', '{"q1xxxxxx":5,"q2xxxxxx":9,"q5xxxxxx":true,"q6xxxxxx":"sophie.l24@example.com"}'::jsonb, now() - interval '31732 minutes', date_trunc('month', now() - interval '31732 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000q', 1, 1, null, 'j.smith25@example.com', '{"q1xxxxxx":5,"q2xxxxxx":9,"q3xxxxxx":"Quick answers by phone.","q5xxxxxx":true,"q6xxxxxx":"j.smith25@example.com"}'::jsonb, now() - interval '34553 minutes', date_trunc('month', now() - interval '34553 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000r', 1, 1, null, null, '{"q1xxxxxx":5,"q2xxxxxx":9,"q3xxxxxx":"Delivery was on time and the team was lovely.","q5xxxxxx":false}'::jsonb, now() - interval '37742 minutes', date_trunc('month', now() - interval '37742 minutes')::date, 'fr');

insert into forms (id, slug, owner, status, audience, anonymous, once, tell_team, layout, accent, draft, revision, version, closes_at, max_answers, thanks_title, thanks_body, redirect_url, send_copy, retention_months, answer_count, bell_at, created_at, updated_at, published_at, closed_at)
overriding system value values (2, 'p4x8vn2c', 'mbr_camilleaaaaaaaaaaaaaaaaaaa', 'published', 'public', false, true, false, 'classic', 'tangerine', '{"title":"Open day — Saturday 14 November","intro":"Come and see the workshop at work. Tell us you are coming and we will save you a seat.","pages":[{"id":"plxxxxxx","title":"","questions":[{"id":"qbxxxxxx","kind":"short","title":"Your full name","help":"","required":true},{"id":"qcxxxxxx","kind":"email","title":"Your email address","help":"","required":true},{"id":"qdxxxxxx","kind":"short","title":"Your company","help":"","required":false},{"id":"qexxxxxx","kind":"number","title":"How many people are you?","help":"","required":true,"min":1,"max":10},{"id":"qkxxxxxx","kind":"choice","title":"Which workshop tour?","help":"","required":true,"options":[{"id":"ohxxxxxx","label":"10:00 — Wood and finishes"},{"id":"oixxxxxx","label":"14:00 — Upholstery"},{"id":"ojxxxxxx","label":"16:00 — Restoration"}]},{"id":"qfxxxxxx","kind":"yesno","title":"Will you stay for lunch?","help":"","required":true},{"id":"qgxxxxxx","kind":"short","title":"Any food we should know about?","help":"","required":false,"showIf":{"question":"qfxxxxxx","op":"is","value":true}}],"jumps":[]}],"language":"en","alt":{"language":"fr","texts":{"title":"Portes ouvertes — samedi 14 novembre","intro":"Venez voir l’atelier au travail. Dites-nous que vous venez, nous vous garderons une place.","qbxxxxxx":"Vos nom et prénom","qcxxxxxx":"Votre adresse e-mail","qdxxxxxx":"Votre entreprise","qexxxxxx":"Combien serez-vous ?","qkxxxxxx":"Quelle visite d’atelier ?","qkxxxxxx.ohxxxxxx":"10 h — Bois et finitions","qkxxxxxx.oixxxxxx":"14 h — Tapisserie","qkxxxxxx.ojxxxxxx":"16 h — Restauration","qfxxxxxx":"Resterez-vous déjeuner ?","qgxxxxxx":"Un régime alimentaire à connaître ?"}}}'::jsonb, 3, 1, date_trunc('day', now()) + interval '46 days 17 hours', 60, '', '', null, true, null, 11, now() - interval '2 hours', now() - interval '12 days', now() - interval '1 days', now() - interval '11 days', null);
insert into versions (form_id, version, definition, published_at) values (2, 1, '{"title":"Open day — Saturday 14 November","intro":"Come and see the workshop at work. Tell us you are coming and we will save you a seat.","pages":[{"id":"plxxxxxx","title":"","questions":[{"id":"qbxxxxxx","kind":"short","title":"Your full name","help":"","required":true},{"id":"qcxxxxxx","kind":"email","title":"Your email address","help":"","required":true},{"id":"qdxxxxxx","kind":"short","title":"Your company","help":"","required":false},{"id":"qexxxxxx","kind":"number","title":"How many people are you?","help":"","required":true,"min":1,"max":10},{"id":"qkxxxxxx","kind":"choice","title":"Which workshop tour?","help":"","required":true,"options":[{"id":"ohxxxxxx","label":"10:00 — Wood and finishes"},{"id":"oixxxxxx","label":"14:00 — Upholstery"},{"id":"ojxxxxxx","label":"16:00 — Restoration"}]},{"id":"qfxxxxxx","kind":"yesno","title":"Will you stay for lunch?","help":"","required":true},{"id":"qgxxxxxx","kind":"short","title":"Any food we should know about?","help":"","required":false,"showIf":{"question":"qfxxxxxx","op":"is","value":true}}],"jumps":[]}],"language":"en","alt":{"language":"fr","texts":{"title":"Portes ouvertes — samedi 14 novembre","intro":"Venez voir l’atelier au travail. Dites-nous que vous venez, nous vous garderons une place.","qbxxxxxx":"Vos nom et prénom","qcxxxxxx":"Votre adresse e-mail","qdxxxxxx":"Votre entreprise","qexxxxxx":"Combien serez-vous ?","qkxxxxxx":"Quelle visite d’atelier ?","qkxxxxxx.ohxxxxxx":"10 h — Bois et finitions","qkxxxxxx.oixxxxxx":"14 h — Tapisserie","qkxxxxxx.ojxxxxxx":"16 h — Restauration","qfxxxxxx":"Resterez-vous déjeuner ?","qgxxxxxx":"Un régime alimentaire à connaître ?"}}}'::jsonb, now() - interval '11 days');
insert into watchers (form_id, member, unseen) values (2, 'mbr_camilleaaaaaaaaaaaaaaaaaaa', 2);
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000s', 2, 1, null, 'elodie.garnier@example.fr', '{"qbxxxxxx":"Élodie Garnier","qcxxxxxx":"elodie.garnier@example.fr","qexxxxxx":2,"qkxxxxxx":{"ids":["ojxxxxxx"]},"qfxxxxxx":true,"qdxxxxxx":"Studio Garnier"}'::jsonb, now() - interval '277 minutes', date_trunc('month', now() - interval '277 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000t', 2, 1, null, 'tom.hughes@example.co.uk', '{"qbxxxxxx":"Tom Hughes","qcxxxxxx":"tom.hughes@example.co.uk","qexxxxxx":1,"qkxxxxxx":{"ids":["ohxxxxxx"]},"qfxxxxxx":true,"qgxxxxxx":"Vegan"}'::jsonb, now() - interval '949 minutes', date_trunc('month', now() - interval '949 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000u', 2, 1, null, 'nadia@benali-design.example', '{"qbxxxxxx":"Nadia Benali","qcxxxxxx":"nadia@benali-design.example","qexxxxxx":3,"qkxxxxxx":{"ids":["ohxxxxxx"]},"qfxxxxxx":true,"qdxxxxxx":"Benali Design","qgxxxxxx":"Vegetarian"}'::jsonb, now() - interval '1609 minutes', date_trunc('month', now() - interval '1609 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000v', 2, 1, null, 'luc.moreau@example.fr', '{"qbxxxxxx":"Luc Moreau","qcxxxxxx":"luc.moreau@example.fr","qexxxxxx":3,"qkxxxxxx":{"ids":["ojxxxxxx"]},"qfxxxxxx":true,"qdxxxxxx":"Mairie de Vincennes"}'::jsonb, now() - interval '2216 minutes', date_trunc('month', now() - interval '2216 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000w', 2, 1, null, 's.klein@example.de', '{"qbxxxxxx":"Sarah Klein","qcxxxxxx":"s.klein@example.de","qexxxxxx":1,"qkxxxxxx":{"ids":["oixxxxxx"]},"qfxxxxxx":true}'::jsonb, now() - interval '3028 minutes', date_trunc('month', now() - interval '3028 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000x', 2, 1, null, 'paul.durand@example.org', '{"qbxxxxxx":"Paul Durand","qcxxxxxx":"paul.durand@example.org","qexxxxxx":3,"qkxxxxxx":{"ids":["oixxxxxx"]},"qfxxxxxx":true,"qdxxxxxx":"Durand & Fils","qgxxxxxx":"Vegetarian"}'::jsonb, now() - interval '3649 minutes', date_trunc('month', now() - interval '3649 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000y', 2, 1, null, 'inga@example.no', '{"qbxxxxxx":"Inga Larsen","qcxxxxxx":"inga@example.no","qexxxxxx":1,"qkxxxxxx":{"ids":["ojxxxxxx"]},"qfxxxxxx":true}'::jsonb, now() - interval '4330 minutes', date_trunc('month', now() - interval '4330 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000000z', 2, 1, null, 'mehdi.rahal@example.fr', '{"qbxxxxxx":"Mehdi Rahal","qcxxxxxx":"mehdi.rahal@example.fr","qexxxxxx":2,"qkxxxxxx":{"ids":["ohxxxxxx"]},"qfxxxxxx":true,"qdxxxxxx":"Rahal Immobilier","qgxxxxxx":"Vegan"}'::jsonb, now() - interval '5234 minutes', date_trunc('month', now() - interval '5234 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000010', 2, 1, null, 'julie.petit@example.fr', '{"qbxxxxxx":"Julie Petit","qcxxxxxx":"julie.petit@example.fr","qexxxxxx":3,"qkxxxxxx":{"ids":["ojxxxxxx"]},"qfxxxxxx":true}'::jsonb, now() - interval '5888 minutes', date_trunc('month', now() - interval '5888 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000011', 2, 1, null, 'a.blanc@example.fr', '{"qbxxxxxx":"Arthur Blanc","qcxxxxxx":"a.blanc@example.fr","qexxxxxx":3,"qkxxxxxx":{"ids":["ojxxxxxx"]},"qfxxxxxx":true,"qdxxxxxx":"Atelier Blanc"}'::jsonb, now() - interval '6400 minutes', date_trunc('month', now() - interval '6400 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000012', 2, 1, null, 'chiara.conti@example.it', '{"qbxxxxxx":"Chiara Conti","qcxxxxxx":"chiara.conti@example.it","qexxxxxx":1,"qkxxxxxx":{"ids":["ohxxxxxx"]},"qfxxxxxx":false}'::jsonb, now() - interval '7062 minutes', date_trunc('month', now() - interval '7062 minutes')::date, 'en');

insert into forms (id, slug, owner, status, audience, anonymous, once, tell_team, layout, accent, draft, revision, version, closes_at, max_answers, thanks_title, thanks_body, redirect_url, send_copy, retention_months, answer_count, bell_at, created_at, updated_at, published_at, closed_at)
overriding system value values (3, 't9r3hw6b', 'mbr_camilleaaaaaaaaaaaaaaaaaaa', 'published', 'team', false, false, false, 'classic', 'teal', '{"title":"IT request","intro":"Tell us what is wrong. We come back to you quickly.","pages":[{"id":"p11xxxxx","title":"","questions":[{"id":"qpxxxxxx","kind":"choice","title":"What do you need?","help":"","required":true,"options":[{"id":"omxxxxxx","label":"Something is broken"},{"id":"onxxxxxx","label":"New equipment"},{"id":"ooxxxxxx","label":"Access to a tool"}],"other":true},{"id":"quxxxxxx","kind":"dropdown","title":"Which device?","help":"","required":false,"options":[{"id":"oqxxxxxx","label":"Laptop"},{"id":"orxxxxxx","label":"Phone"},{"id":"osxxxxxx","label":"Printer"},{"id":"otxxxxxx","label":"Screen"}],"showIf":{"question":"qpxxxxxx","op":"is_not","value":"ooxxxxxx"}},{"id":"qyxxxxxx","kind":"choice","title":"How urgent is it?","help":"","required":true,"options":[{"id":"ovxxxxxx","label":"I cannot work"},{"id":"owxxxxxx","label":"It slows me down"},{"id":"oxxxxxxx","label":"It can wait"}]},{"id":"qzxxxxxx","kind":"long","title":"Describe it in a few words","help":"","required":true},{"id":"q10xxxxx","kind":"file","title":"A photo or a screenshot","help":"","required":false,"accept":"images"}],"jumps":[]}],"language":"en","alt":{"language":"fr","texts":{"title":"Demande informatique","intro":"Dites-nous ce qui ne va pas. Nous revenons vers vous vite.","qpxxxxxx":"De quoi avez-vous besoin ?","qpxxxxxx.omxxxxxx":"Quelque chose est en panne","qpxxxxxx.onxxxxxx":"Un nouvel équipement","qpxxxxxx.ooxxxxxx":"Un accès à un outil","quxxxxxx":"Quel appareil ?","quxxxxxx.oqxxxxxx":"Ordinateur portable","quxxxxxx.orxxxxxx":"Téléphone","quxxxxxx.osxxxxxx":"Imprimante","quxxxxxx.otxxxxxx":"Écran","qyxxxxxx":"C’est urgent ?","qyxxxxxx.ovxxxxxx":"Je ne peux pas travailler","qyxxxxxx.owxxxxxx":"Ça me ralentit","qyxxxxxx.oxxxxxxx":"Ça peut attendre","qzxxxxxx":"Décrivez-le en quelques mots","q10xxxxx":"Une photo ou une capture d’écran"}}}'::jsonb, 3, 1, null, null, '', '', null, true, null, 6, now() - interval '2 hours', now() - interval '60 days', now() - interval '1 days', now() - interval '59 days', null);
insert into versions (form_id, version, definition, published_at) values (3, 1, '{"title":"IT request","intro":"Tell us what is wrong. We come back to you quickly.","pages":[{"id":"p11xxxxx","title":"","questions":[{"id":"qpxxxxxx","kind":"choice","title":"What do you need?","help":"","required":true,"options":[{"id":"omxxxxxx","label":"Something is broken"},{"id":"onxxxxxx","label":"New equipment"},{"id":"ooxxxxxx","label":"Access to a tool"}],"other":true},{"id":"quxxxxxx","kind":"dropdown","title":"Which device?","help":"","required":false,"options":[{"id":"oqxxxxxx","label":"Laptop"},{"id":"orxxxxxx","label":"Phone"},{"id":"osxxxxxx","label":"Printer"},{"id":"otxxxxxx","label":"Screen"}],"showIf":{"question":"qpxxxxxx","op":"is_not","value":"ooxxxxxx"}},{"id":"qyxxxxxx","kind":"choice","title":"How urgent is it?","help":"","required":true,"options":[{"id":"ovxxxxxx","label":"I cannot work"},{"id":"owxxxxxx","label":"It slows me down"},{"id":"oxxxxxxx","label":"It can wait"}]},{"id":"qzxxxxxx","kind":"long","title":"Describe it in a few words","help":"","required":true},{"id":"q10xxxxx","kind":"file","title":"A photo or a screenshot","help":"","required":false,"accept":"images"}],"jumps":[]}],"language":"en","alt":{"language":"fr","texts":{"title":"Demande informatique","intro":"Dites-nous ce qui ne va pas. Nous revenons vers vous vite.","qpxxxxxx":"De quoi avez-vous besoin ?","qpxxxxxx.omxxxxxx":"Quelque chose est en panne","qpxxxxxx.onxxxxxx":"Un nouvel équipement","qpxxxxxx.ooxxxxxx":"Un accès à un outil","quxxxxxx":"Quel appareil ?","quxxxxxx.oqxxxxxx":"Ordinateur portable","quxxxxxx.orxxxxxx":"Téléphone","quxxxxxx.osxxxxxx":"Imprimante","quxxxxxx.otxxxxxx":"Écran","qyxxxxxx":"C’est urgent ?","qyxxxxxx.ovxxxxxx":"Je ne peux pas travailler","qyxxxxxx.owxxxxxx":"Ça me ralentit","qyxxxxxx.oxxxxxxx":"Ça peut attendre","qzxxxxxx":"Décrivez-le en quelques mots","q10xxxxx":"Une photo ou une capture d’écran"}}}'::jsonb, now() - interval '59 days');
insert into access (form_id, member, level) values (3, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', 'editor');
insert into watchers (form_id, member, unseen) values (3, 'mbr_camilleaaaaaaaaaaaaaaaaaaa', 1);
insert into watchers (form_id, member, unseen) values (3, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', 0);
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000013', 3, 1, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', null, '{"qpxxxxxx":{"ids":["omxxxxxx"]},"qyxxxxxx":{"ids":["owxxxxxx"]},"qzxxxxxx":"My laptop fan is very loud since Monday.","quxxxxxx":{"ids":["oqxxxxxx"]}}'::jsonb, now() - interval '45 minutes', date_trunc('month', now() - interval '45 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000014', 3, 1, 'mbr_leaaaaaaaaaaaaaaaaaaaaaaaa', null, '{"qpxxxxxx":{"ids":["ooxxxxxx"]},"qyxxxxxx":{"ids":["oxxxxxxx"]},"qzxxxxxx":"I need access to the accounting tool for the month-end."}'::jsonb, now() - interval '2345 minutes', date_trunc('month', now() - interval '2345 minutes')::date, 'fr');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000015', 3, 1, 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', null, '{"qpxxxxxx":{"ids":["omxxxxxx"]},"qyxxxxxx":{"ids":["ovxxxxxx"]},"qzxxxxxx":"The printer on the first floor jams on every page.","quxxxxxx":{"ids":["osxxxxxx"]}}'::jsonb, now() - interval '4645 minutes', date_trunc('month', now() - interval '4645 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000016', 3, 1, 'mbr_tomaaaaaaaaaaaaaaaaaaaaaaa', null, '{"qpxxxxxx":{"ids":["onxxxxxx"]},"qyxxxxxx":{"ids":["oxxxxxxx"]},"qzxxxxxx":"A second screen for the design desk, please.","quxxxxxx":{"ids":["otxxxxxx"]}}'::jsonb, now() - interval '6945 minutes', date_trunc('month', now() - interval '6945 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000017', 3, 1, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', null, '{"qpxxxxxx":{"ids":["omxxxxxx"]},"qyxxxxxx":{"ids":["owxxxxxx"]},"qzxxxxxx":"The phone does not charge any more.","quxxxxxx":{"ids":["orxxxxxx"]}}'::jsonb, now() - interval '9245 minutes', date_trunc('month', now() - interval '9245 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000018', 3, 1, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', null, '{"qpxxxxxx":{"ids":["onxxxxxx"]},"qyxxxxxx":{"ids":["oxxxxxxx"]},"qzxxxxxx":"A laptop for our new salesperson who starts on 2 November.","quxxxxxx":{"ids":["oqxxxxxx"]}}'::jsonb, now() - interval '11545 minutes', date_trunc('month', now() - interval '11545 minutes')::date, 'fr');

insert into forms (id, slug, owner, status, audience, anonymous, once, tell_team, layout, accent, draft, revision, version, closes_at, max_answers, thanks_title, thanks_body, redirect_url, send_copy, retention_months, answer_count, bell_at, created_at, updated_at, published_at, closed_at)
overriding system value values (4, 'w5c8ja3e', 'mbr_camilleaaaaaaaaaaaaaaaaaaa', 'published', 'team', true, true, false, 'steps', 'ink', '{"title":"How was your week?","intro":"Anonymous: nobody sees who answered what.","pages":[{"id":"p1axxxxx","title":"","questions":[{"id":"q12xxxxx","kind":"rating","title":"How was your week overall?","help":"","required":true,"steps":5},{"id":"q13xxxxx","kind":"scale","title":"How was your workload?","help":"","required":true,"from":1,"to":5,"left":"Too light","right":"Too heavy"},{"id":"q18xxxxx","kind":"choices","title":"What helped you most this week?","help":"","required":false,"options":[{"id":"o14xxxxx","label":"My colleagues"},{"id":"o15xxxxx","label":"Our tools"},{"id":"o16xxxxx","label":"Time to focus"},{"id":"o17xxxxx","label":"Being thanked"}],"max":2},{"id":"q19xxxxx","kind":"long","title":"One thing we could change","help":"","required":false}],"jumps":[]}],"language":"en","alt":{"language":"fr","texts":{"title":"Comment était votre semaine ?","intro":"Anonyme : personne ne voit qui a répondu quoi.","q12xxxxx":"Comment s’est passée votre semaine ?","q13xxxxx":"Votre charge de travail ?","q13xxxxx.left":"Trop légère","q13xxxxx.right":"Trop lourde","q18xxxxx":"Qu’est-ce qui vous a le plus aidé cette semaine ?","q18xxxxx.o14xxxxx":"Mes collègues","q18xxxxx.o15xxxxx":"Nos outils","q18xxxxx.o16xxxxx":"Du temps pour me concentrer","q18xxxxx.o17xxxxx":"Être remercié","q19xxxxx":"Une chose que nous pourrions changer"}}}'::jsonb, 3, 1, null, null, '', '', null, false, 6, 5, now() - interval '2 hours', now() - interval '3 days', now() - interval '1 days', now() - interval '2 days', null);
insert into versions (form_id, version, definition, published_at) values (4, 1, '{"title":"How was your week?","intro":"Anonymous: nobody sees who answered what.","pages":[{"id":"p1axxxxx","title":"","questions":[{"id":"q12xxxxx","kind":"rating","title":"How was your week overall?","help":"","required":true,"steps":5},{"id":"q13xxxxx","kind":"scale","title":"How was your workload?","help":"","required":true,"from":1,"to":5,"left":"Too light","right":"Too heavy"},{"id":"q18xxxxx","kind":"choices","title":"What helped you most this week?","help":"","required":false,"options":[{"id":"o14xxxxx","label":"My colleagues"},{"id":"o15xxxxx","label":"Our tools"},{"id":"o16xxxxx","label":"Time to focus"},{"id":"o17xxxxx","label":"Being thanked"}],"max":2},{"id":"q19xxxxx","kind":"long","title":"One thing we could change","help":"","required":false}],"jumps":[]}],"language":"en","alt":{"language":"fr","texts":{"title":"Comment était votre semaine ?","intro":"Anonyme : personne ne voit qui a répondu quoi.","q12xxxxx":"Comment s’est passée votre semaine ?","q13xxxxx":"Votre charge de travail ?","q13xxxxx.left":"Trop légère","q13xxxxx.right":"Trop lourde","q18xxxxx":"Qu’est-ce qui vous a le plus aidé cette semaine ?","q18xxxxx.o14xxxxx":"Mes collègues","q18xxxxx.o15xxxxx":"Nos outils","q18xxxxx.o16xxxxx":"Du temps pour me concentrer","q18xxxxx.o17xxxxx":"Être remercié","q19xxxxx":"Une chose que nous pourrions changer"}}}'::jsonb, now() - interval '2 days');
insert into watchers (form_id, member, unseen) values (4, 'mbr_camilleaaaaaaaaaaaaaaaaaaa', 0);
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000019', 4, 1, null, null, '{"q12xxxxx":4,"q13xxxxx":5,"q18xxxxx":{"ids":["o14xxxxx"]},"q19xxxxx":"More quiet time on Friday mornings."}'::jsonb, null, date_trunc('month', now() - interval '10 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000001a', 4, 1, null, null, '{"q12xxxxx":4,"q13xxxxx":3,"q18xxxxx":{"ids":["o16xxxxx"]}}'::jsonb, null, date_trunc('month', now() - interval '10 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000001b', 4, 1, null, null, '{"q12xxxxx":4,"q13xxxxx":4,"q18xxxxx":{"ids":["o17xxxxx"]},"q19xxxxx":"A shared calendar for the van."}'::jsonb, null, date_trunc('month', now() - interval '10 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000001c', 4, 1, null, null, '{"q12xxxxx":5,"q13xxxxx":4,"q18xxxxx":{"ids":["o17xxxxx"]}}'::jsonb, null, date_trunc('month', now() - interval '10 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000001d', 4, 1, null, null, '{"q12xxxxx":5,"q13xxxxx":4,"q18xxxxx":{"ids":["o14xxxxx"]},"q19xxxxx":"Coffee machine on the first floor!"}'::jsonb, null, date_trunc('month', now() - interval '10 minutes')::date, 'en');
insert into participants (form_id, member) values (4, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa');
insert into participants (form_id, member) values (4, 'mbr_leaaaaaaaaaaaaaaaaaaaaaaaa');
insert into participants (form_id, member) values (4, 'mbr_camilleaaaaaaaaaaaaaaaaaaa');
insert into participants (form_id, member) values (4, 'mbr_tomaaaaaaaaaaaaaaaaaaaaaaa');
insert into participants (form_id, member) values (4, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa');

insert into forms (id, slug, owner, status, audience, anonymous, once, tell_team, layout, accent, draft, revision, version, closes_at, max_answers, thanks_title, thanks_body, redirect_url, send_copy, retention_months, answer_count, bell_at, created_at, updated_at, published_at, closed_at)
overriding system value values (5, 'c2n6yd8u', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 'draft', 'public', false, true, false, 'classic', 'indigo', '{"title":"Contact us","intro":"Tell us what you need. We answer within one working day.","pages":[{"id":"p1jxxxxx","title":"","questions":[{"id":"q1bxxxxx","kind":"short","title":"Your name","help":"","required":true},{"id":"q1cxxxxx","kind":"email","title":"Your email address","help":"","required":true},{"id":"q1dxxxxx","kind":"phone","title":"Your phone number","help":"","required":false},{"id":"q1hxxxxx","kind":"choice","title":"What is it about?","help":"","required":true,"options":[{"id":"o1exxxxx","label":"A question"},{"id":"o1fxxxxx","label":"A quote"},{"id":"o1gxxxxx","label":"An order"}],"other":true},{"id":"q1ixxxxx","kind":"long","title":"Your message","help":"","required":true,"max":2000}],"jumps":[]}],"language":"en","alt":{"language":"fr","texts":{"title":"Contactez-nous","intro":"Dites-nous ce dont vous avez besoin. Nous répondons sous un jour ouvré.","q1bxxxxx":"Votre nom","q1cxxxxx":"Votre adresse e-mail","q1dxxxxx":"Votre numéro de téléphone","q1hxxxxx":"C’est à quel sujet ?","q1hxxxxx.o1exxxxx":"Une question","q1hxxxxx.o1fxxxxx":"Un devis","q1hxxxxx.o1gxxxxx":"Une commande","q1ixxxxx":"Votre message"}}}'::jsonb, 3, 0, null, null, '', '', null, false, null, 0, now() - interval '2 hours', now() - interval '1 days', now() - interval '0 days', null, null);
insert into watchers (form_id, member, unseen) values (5, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 0);

insert into forms (id, slug, owner, status, audience, anonymous, once, tell_team, layout, accent, draft, revision, version, closes_at, max_answers, thanks_title, thanks_body, redirect_url, send_copy, retention_months, answer_count, bell_at, created_at, updated_at, published_at, closed_at)
overriding system value values (6, 's8f4ku7m', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 'closed', 'public', false, true, false, 'classic', 'forest', '{"title":"Summer workshop helpers","intro":"Students who want to learn the trade for a week.","pages":[{"id":"p1pxxxxx","title":"","questions":[{"id":"q1kxxxxx","kind":"short","title":"Your name","help":"","required":true},{"id":"q1oxxxxx","kind":"choices","title":"Which weeks can you help?","help":"","required":true,"options":[{"id":"o1lxxxxx","label":"6–10 July"},{"id":"o1mxxxxx","label":"13–17 July"},{"id":"o1nxxxxx","label":"20–24 July"}]}],"jumps":[]}],"language":"en","alt":{"language":"fr","texts":{"title":"Renforts d’été à l’atelier","intro":"Des élèves qui veulent apprendre le métier pendant une semaine.","q1kxxxxx":"Votre nom","q1oxxxxx":"Quelles semaines pouvez-vous aider ?","q1oxxxxx.o1lxxxxx":"6–10 juillet","q1oxxxxx.o1mxxxxx":"13–17 juillet","q1oxxxxx.o1nxxxxx":"20–24 juillet"}}}'::jsonb, 3, 1, null, null, '', '', null, false, null, 4, now() - interval '2 hours', now() - interval '110 days', now() - interval '1 days', now() - interval '109 days', now() - interval '5 days');
insert into versions (form_id, version, definition, published_at) values (6, 1, '{"title":"Summer workshop helpers","intro":"Students who want to learn the trade for a week.","pages":[{"id":"p1pxxxxx","title":"","questions":[{"id":"q1kxxxxx","kind":"short","title":"Your name","help":"","required":true},{"id":"q1oxxxxx","kind":"choices","title":"Which weeks can you help?","help":"","required":true,"options":[{"id":"o1lxxxxx","label":"6–10 July"},{"id":"o1mxxxxx","label":"13–17 July"},{"id":"o1nxxxxx","label":"20–24 July"}]}],"jumps":[]}],"language":"en","alt":{"language":"fr","texts":{"title":"Renforts d’été à l’atelier","intro":"Des élèves qui veulent apprendre le métier pendant une semaine.","q1kxxxxx":"Votre nom","q1oxxxxx":"Quelles semaines pouvez-vous aider ?","q1oxxxxx.o1lxxxxx":"6–10 juillet","q1oxxxxx.o1mxxxxx":"13–17 juillet","q1oxxxxx.o1nxxxxx":"20–24 juillet"}}}'::jsonb, now() - interval '109 days');
insert into watchers (form_id, member, unseen) values (6, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 0);
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000001e', 6, 1, null, null, '{"q1kxxxxx":"Léon","q1oxxxxx":{"ids":["o1lxxxxx"]}}'::jsonb, now() - interval '100800 minutes', date_trunc('month', now() - interval '100800 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000001f', 6, 1, null, null, '{"q1kxxxxx":"Maya","q1oxxxxx":{"ids":["o1mxxxxx"]}}'::jsonb, now() - interval '102240 minutes', date_trunc('month', now() - interval '102240 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000001g', 6, 1, null, null, '{"q1kxxxxx":"Sami","q1oxxxxx":{"ids":["o1nxxxxx"]}}'::jsonb, now() - interval '103680 minutes', date_trunc('month', now() - interval '103680 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed00000000001h', 6, 1, null, null, '{"q1kxxxxx":"Zoé","q1oxxxxx":{"ids":["o1lxxxxx"]}}'::jsonb, now() - interval '105120 minutes', date_trunc('month', now() - interval '105120 minutes')::date, 'en');

-- Second step (migration 0002): the forms say their language, the open day
-- has a French version, the IT requests are followed up, a team survey
-- uses a matrix and a ranking, the feedback form emails Inès each batch
-- and tells the other tools of each answer.
update forms set draft = jsonb_set(draft, '{language}', '"en"') where id in (1, 3, 4, 5, 6);
update versions set definition = jsonb_set(definition, '{language}', '"en"') where form_id in (1, 3, 4, 6);
update forms set draft = jsonb_set(jsonb_set(draft, '{language}', '"en"'), '{alt}', '{"language": "fr", "texts": {"title": "Portes ouvertes — samedi 14 novembre", "intro": "Venez voir l’atelier au travail. Dites-nous que vous venez et nous vous garderons une place.", "qbxxxxxx": "Votre nom complet", "qcxxxxxx": "Votre adresse e-mail", "qdxxxxxx": "Votre entreprise", "qexxxxxx": "Combien serez-vous ?", "qkxxxxxx": "Quelle visite de l’atelier ?", "qkxxxxxx.ohxxxxxx": "10:00 — Bois et finitions", "qkxxxxxx.oixxxxxx": "14:00 — Tapisserie", "qkxxxxxx.ojxxxxxx": "16:00 — Restauration", "qfxxxxxx": "Resterez-vous déjeuner ?", "qgxxxxxx": "Un régime alimentaire à connaître ?"}}'::jsonb) where id = 2;
update versions set definition = jsonb_set(jsonb_set(definition, '{language}', '"en"'), '{alt}', '{"language": "fr", "texts": {"title": "Portes ouvertes — samedi 14 novembre", "intro": "Venez voir l’atelier au travail. Dites-nous que vous venez et nous vous garderons une place.", "qbxxxxxx": "Votre nom complet", "qcxxxxxx": "Votre adresse e-mail", "qdxxxxxx": "Votre entreprise", "qexxxxxx": "Combien serez-vous ?", "qkxxxxxx": "Quelle visite de l’atelier ?", "qkxxxxxx.ohxxxxxx": "10:00 — Bois et finitions", "qkxxxxxx.oixxxxxx": "14:00 — Tapisserie", "qkxxxxxx.ojxxxxxx": "16:00 — Restauration", "qfxxxxxx": "Resterez-vous déjeuner ?", "qgxxxxxx": "Un régime alimentaire à connaître ?"}}'::jsonb) where form_id = 2;
update forms set notify_email = true, share_events = true where id = 1;
update answers set status = 'done', note = 'A new charger is on your desk.', handled_at = now() - interval '1 day' where id = 'seed000000000013';
update answers set status = 'doing', note = 'Ordered, it arrives on Thursday.' where id = 'seed000000000014';
update answers set status = 'done', handled_at = now() - interval '2 days' where id = 'seed000000000016';
insert into forms (id, slug, owner, status, audience, anonymous, once, tell_team, layout, accent, draft, revision, version, answer_count, created_at, updated_at, published_at)
overriding system value values (7, 'v6m3tq8r', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 'published', 'team', false, true, false, 'classic', 'forest', '{"title":"Our new workshop — your view","intro":"Three questions, one minute. It helps us plan the next changes.","pages":[{"id":"p7axxxxx","title":"","questions":[{"id":"q30xxxxx","kind":"matrix","title":"How is the new workshop for you?","help":"","required":true,"rows":[{"id":"r31xxxxx","label":"Light"},{"id":"r32xxxxx","label":"Noise"},{"id":"r33xxxxx","label":"Space at the bench"},{"id":"r34xxxxx","label":"Tools at hand"}],"options":[{"id":"c35xxxxx","label":"Poor"},{"id":"c36xxxxx","label":"Fair"},{"id":"c37xxxxx","label":"Good"},{"id":"c38xxxxx","label":"Excellent"}]},{"id":"q40xxxxx","kind":"ranking","title":"What should we improve first?","help":"","required":true,"options":[{"id":"i41xxxxx","label":"Bigger benches"},{"id":"i42xxxxx","label":"A quieter finishing room"},{"id":"i43xxxxx","label":"Better light"},{"id":"i44xxxxx","label":"A coffee corner"}]},{"id":"q45xxxxx","kind":"long","title":"Anything else?","help":"","required":false}],"jumps":[]}],"language":"en","alt":{"language":"fr","texts":{"title":"Notre nouvel atelier — votre avis","intro":"Trois questions, une minute. Cela nous aide à préparer les prochains changements.","q30xxxxx":"Comment trouvez-vous le nouvel atelier ?","q30xxxxx.c35xxxxx":"Mauvais","q30xxxxx.c36xxxxx":"Moyen","q30xxxxx.c37xxxxx":"Bien","q30xxxxx.c38xxxxx":"Excellent","q30xxxxx.r31xxxxx":"Lumière","q30xxxxx.r32xxxxx":"Le bruit","q30xxxxx.r33xxxxx":"De la place à l’établi","q30xxxxx.r34xxxxx":"Des outils à portée de main","q40xxxxx":"Que devrions-nous améliorer en premier ?","q40xxxxx.i41xxxxx":"Des établis plus grands","q40xxxxx.i42xxxxx":"Une salle de finition plus calme","q40xxxxx.i43xxxxx":"Une meilleure lumière","q40xxxxx.i44xxxxx":"Un coin café","q45xxxxx":"Autre chose ?"}}}'::jsonb, 2, 1, 5, now() - interval '3 days', now() - interval '3 days', now() - interval '3 days');
insert into versions (form_id, version, definition, published_at) values (7, 1, '{"title":"Our new workshop — your view","intro":"Three questions, one minute. It helps us plan the next changes.","pages":[{"id":"p7axxxxx","title":"","questions":[{"id":"q30xxxxx","kind":"matrix","title":"How is the new workshop for you?","help":"","required":true,"rows":[{"id":"r31xxxxx","label":"Light"},{"id":"r32xxxxx","label":"Noise"},{"id":"r33xxxxx","label":"Space at the bench"},{"id":"r34xxxxx","label":"Tools at hand"}],"options":[{"id":"c35xxxxx","label":"Poor"},{"id":"c36xxxxx","label":"Fair"},{"id":"c37xxxxx","label":"Good"},{"id":"c38xxxxx","label":"Excellent"}]},{"id":"q40xxxxx","kind":"ranking","title":"What should we improve first?","help":"","required":true,"options":[{"id":"i41xxxxx","label":"Bigger benches"},{"id":"i42xxxxx","label":"A quieter finishing room"},{"id":"i43xxxxx","label":"Better light"},{"id":"i44xxxxx","label":"A coffee corner"}]},{"id":"q45xxxxx","kind":"long","title":"Anything else?","help":"","required":false}],"jumps":[]}],"language":"en","alt":{"language":"fr","texts":{"title":"Notre nouvel atelier — votre avis","intro":"Trois questions, une minute. Cela nous aide à préparer les prochains changements.","q30xxxxx":"Comment trouvez-vous le nouvel atelier ?","q30xxxxx.c35xxxxx":"Mauvais","q30xxxxx.c36xxxxx":"Moyen","q30xxxxx.c37xxxxx":"Bien","q30xxxxx.c38xxxxx":"Excellent","q30xxxxx.r31xxxxx":"Lumière","q30xxxxx.r32xxxxx":"Le bruit","q30xxxxx.r33xxxxx":"De la place à l’établi","q30xxxxx.r34xxxxx":"Des outils à portée de main","q40xxxxx":"Que devrions-nous améliorer en premier ?","q40xxxxx.i41xxxxx":"Des établis plus grands","q40xxxxx.i42xxxxx":"Une salle de finition plus calme","q40xxxxx.i43xxxxx":"Une meilleure lumière","q40xxxxx.i44xxxxx":"Un coin café","q45xxxxx":"Autre chose ?"}}}'::jsonb, now() - interval '3 days');
insert into watchers (form_id, member, unseen) values (7, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 0);
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000020', 7, 1, 'mbr_camilleaaaaaaaaaaaaaaaaaaa', null, '{"q30xxxxx": {"rows": {"r31xxxxx": "c38xxxxx", "r32xxxxx": "c36xxxxx", "r33xxxxx": "c37xxxxx", "r34xxxxx": "c37xxxxx"}}, "q40xxxxx": ["i42xxxxx", "i41xxxxx", "i43xxxxx", "i44xxxxx"], "q45xxxxx": "The finishing room is too loud when the sander runs."}'::jsonb, now() - interval '60 minutes', date_trunc('month', now() - interval '60 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000021', 7, 1, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', null, '{"q30xxxxx": {"rows": {"r31xxxxx": "c37xxxxx", "r32xxxxx": "c35xxxxx", "r33xxxxx": "c36xxxxx", "r34xxxxx": "c37xxxxx"}}, "q40xxxxx": ["i42xxxxx", "i41xxxxx", "i44xxxxx", "i43xxxxx"]}'::jsonb, now() - interval '200 minutes', date_trunc('month', now() - interval '200 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000022', 7, 1, 'mbr_leaaaaaaaaaaaaaaaaaaaaaaaa', null, '{"q30xxxxx": {"rows": {"r31xxxxx": "c38xxxxx", "r32xxxxx": "c36xxxxx", "r33xxxxx": "c35xxxxx", "r34xxxxx": "c36xxxxx"}}, "q40xxxxx": ["i41xxxxx", "i42xxxxx", "i43xxxxx", "i44xxxxx"], "q45xxxxx": "More room at the long bench, please."}'::jsonb, now() - interval '900 minutes', date_trunc('month', now() - interval '900 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000023', 7, 1, 'mbr_tomaaaaaaaaaaaaaaaaaaaaaaa', null, '{"q30xxxxx": {"rows": {"r31xxxxx": "c37xxxxx", "r32xxxxx": "c36xxxxx", "r33xxxxx": "c37xxxxx", "r34xxxxx": "c38xxxxx"}}, "q40xxxxx": ["i44xxxxx", "i42xxxxx", "i41xxxxx", "i43xxxxx"]}'::jsonb, now() - interval '1500 minutes', date_trunc('month', now() - interval '1500 minutes')::date, 'en');
insert into answers (id, form_id, version, respondent, email, data, created_at, month, language) values ('seed000000000024', 7, 1, 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', null, '{"q30xxxxx": {"rows": {"r31xxxxx": "c36xxxxx", "r32xxxxx": "c35xxxxx", "r33xxxxx": "c37xxxxx", "r34xxxxx": "c37xxxxx"}}, "q40xxxxx": ["i42xxxxx", "i43xxxxx", "i41xxxxx", "i44xxxxx"]}'::jsonb, now() - interval '2600 minutes', date_trunc('month', now() - interval '2600 minutes')::date, 'en');

-- Every seeded form has a French version (store critique: a French
-- company's demo reads its forms in French; the English stays first).
update forms set draft = jsonb_set(jsonb_set(draft, '{language}', '"en"'), '{alt}', '{"language": "fr", "texts": {"title": "Comment s’est passée votre expérience ?", "intro": "Deux minutes de votre temps aident beaucoup notre atelier. Merci !", "q1xxxxxx": "Quelle note donnez-vous à notre service ?", "q2xxxxxx": "Recommanderiez-vous l’Atelier Martin à un ami ou à un collègue ?", "q2xxxxxx.left": "Peu probable", "q2xxxxxx.right": "Très probable", "q3xxxxxx": "Qu’avez-vous le plus apprécié ?", "q4xxxxxx": "Que devrions-nous améliorer ?", "q5xxxxxx": "Pouvons-nous vous recontacter au sujet de vos réponses ?", "q6xxxxxx": "Votre adresse e-mail"}}'::jsonb) where id = 1;
update versions set definition = jsonb_set(jsonb_set(definition, '{language}', '"en"'), '{alt}', '{"language": "fr", "texts": {"title": "Comment s’est passée votre expérience ?", "intro": "Deux minutes de votre temps aident beaucoup notre atelier. Merci !", "q1xxxxxx": "Quelle note donnez-vous à notre service ?", "q2xxxxxx": "Recommanderiez-vous l’Atelier Martin à un ami ou à un collègue ?", "q2xxxxxx.left": "Peu probable", "q2xxxxxx.right": "Très probable", "q3xxxxxx": "Qu’avez-vous le plus apprécié ?", "q4xxxxxx": "Que devrions-nous améliorer ?", "q5xxxxxx": "Pouvons-nous vous recontacter au sujet de vos réponses ?", "q6xxxxxx": "Votre adresse e-mail"}}'::jsonb) where form_id = 1;
update forms set draft = jsonb_set(jsonb_set(draft, '{language}', '"en"'), '{alt}', '{"language": "fr", "texts": {"title": "Demande informatique", "intro": "Dites-nous ce qui ne va pas. Nous revenons vers vous rapidement.", "qpxxxxxx": "De quoi avez-vous besoin ?", "qpxxxxxx.omxxxxxx": "Quelque chose est en panne", "qpxxxxxx.onxxxxxx": "Du nouveau matériel", "qpxxxxxx.ooxxxxxx": "Un accès à un outil", "quxxxxxx": "Quel appareil ?", "quxxxxxx.oqxxxxxx": "Ordinateur portable", "quxxxxxx.orxxxxxx": "Téléphone", "quxxxxxx.osxxxxxx": "Imprimante", "quxxxxxx.otxxxxxx": "Écran", "qyxxxxxx": "C’est urgent ?", "qyxxxxxx.ovxxxxxx": "Je ne peux pas travailler", "qyxxxxxx.owxxxxxx": "Cela me ralentit", "qyxxxxxx.oxxxxxxx": "Cela peut attendre", "qzxxxxxx": "Décrivez-le en quelques mots", "q10xxxxx": "Une photo ou une capture d’écran"}}'::jsonb) where id = 3;
update versions set definition = jsonb_set(jsonb_set(definition, '{language}', '"en"'), '{alt}', '{"language": "fr", "texts": {"title": "Demande informatique", "intro": "Dites-nous ce qui ne va pas. Nous revenons vers vous rapidement.", "qpxxxxxx": "De quoi avez-vous besoin ?", "qpxxxxxx.omxxxxxx": "Quelque chose est en panne", "qpxxxxxx.onxxxxxx": "Du nouveau matériel", "qpxxxxxx.ooxxxxxx": "Un accès à un outil", "quxxxxxx": "Quel appareil ?", "quxxxxxx.oqxxxxxx": "Ordinateur portable", "quxxxxxx.orxxxxxx": "Téléphone", "quxxxxxx.osxxxxxx": "Imprimante", "quxxxxxx.otxxxxxx": "Écran", "qyxxxxxx": "C’est urgent ?", "qyxxxxxx.ovxxxxxx": "Je ne peux pas travailler", "qyxxxxxx.owxxxxxx": "Cela me ralentit", "qyxxxxxx.oxxxxxxx": "Cela peut attendre", "qzxxxxxx": "Décrivez-le en quelques mots", "q10xxxxx": "Une photo ou une capture d’écran"}}'::jsonb) where form_id = 3;
update forms set draft = jsonb_set(jsonb_set(draft, '{language}', '"en"'), '{alt}', '{"language": "fr", "texts": {"title": "Comment s’est passée votre semaine ?", "intro": "Anonyme : personne ne voit qui a répondu quoi.", "q12xxxxx": "Dans l’ensemble, comment s’est passée votre semaine ?", "q13xxxxx": "Et votre charge de travail ?", "q13xxxxx.left": "Trop légère", "q13xxxxx.right": "Trop lourde", "q18xxxxx": "Qu’est-ce qui vous a le plus aidé cette semaine ?", "q18xxxxx.o14xxxxx": "Mes collègues", "q18xxxxx.o15xxxxx": "Nos outils", "q18xxxxx.o16xxxxx": "Du temps pour me concentrer", "q18xxxxx.o17xxxxx": "Être remercié", "q19xxxxx": "Une chose que nous pourrions changer"}}'::jsonb) where id = 4;
update versions set definition = jsonb_set(jsonb_set(definition, '{language}', '"en"'), '{alt}', '{"language": "fr", "texts": {"title": "Comment s’est passée votre semaine ?", "intro": "Anonyme : personne ne voit qui a répondu quoi.", "q12xxxxx": "Dans l’ensemble, comment s’est passée votre semaine ?", "q13xxxxx": "Et votre charge de travail ?", "q13xxxxx.left": "Trop légère", "q13xxxxx.right": "Trop lourde", "q18xxxxx": "Qu’est-ce qui vous a le plus aidé cette semaine ?", "q18xxxxx.o14xxxxx": "Mes collègues", "q18xxxxx.o15xxxxx": "Nos outils", "q18xxxxx.o16xxxxx": "Du temps pour me concentrer", "q18xxxxx.o17xxxxx": "Être remercié", "q19xxxxx": "Une chose que nous pourrions changer"}}'::jsonb) where form_id = 4;
update forms set draft = jsonb_set(jsonb_set(draft, '{language}', '"en"'), '{alt}', '{"language": "fr", "texts": {"title": "Nous contacter", "intro": "Dites-nous ce dont vous avez besoin. Nous répondons sous un jour ouvré.", "q1bxxxxx": "Votre nom", "q1cxxxxx": "Votre adresse e-mail", "q1dxxxxx": "Votre numéro de téléphone", "q1hxxxxx": "C’est à quel sujet ?", "q1hxxxxx.o1exxxxx": "Une question", "q1hxxxxx.o1fxxxxx": "Un devis", "q1hxxxxx.o1gxxxxx": "Une commande", "q1ixxxxx": "Votre message"}}'::jsonb) where id = 5;
update versions set definition = jsonb_set(jsonb_set(definition, '{language}', '"en"'), '{alt}', '{"language": "fr", "texts": {"title": "Nous contacter", "intro": "Dites-nous ce dont vous avez besoin. Nous répondons sous un jour ouvré.", "q1bxxxxx": "Votre nom", "q1cxxxxx": "Votre adresse e-mail", "q1dxxxxx": "Votre numéro de téléphone", "q1hxxxxx": "C’est à quel sujet ?", "q1hxxxxx.o1exxxxx": "Une question", "q1hxxxxx.o1fxxxxx": "Un devis", "q1hxxxxx.o1gxxxxx": "Une commande", "q1ixxxxx": "Votre message"}}'::jsonb) where form_id = 5;
update forms set draft = jsonb_set(jsonb_set(draft, '{language}', '"en"'), '{alt}', '{"language": "fr", "texts": {"title": "Aides pour l’atelier d’été", "intro": "Des étudiants qui veulent apprendre le métier pendant une semaine.", "q1kxxxxx": "Votre nom", "q1oxxxxx": "Quelles semaines pouvez-vous venir ?", "q1oxxxxx.o1lxxxxx": "6–10 juillet", "q1oxxxxx.o1mxxxxx": "13–17 juillet", "q1oxxxxx.o1nxxxxx": "20–24 juillet"}}'::jsonb) where id = 6;
update versions set definition = jsonb_set(jsonb_set(definition, '{language}', '"en"'), '{alt}', '{"language": "fr", "texts": {"title": "Aides pour l’atelier d’été", "intro": "Des étudiants qui veulent apprendre le métier pendant une semaine.", "q1kxxxxx": "Votre nom", "q1oxxxxx": "Quelles semaines pouvez-vous venir ?", "q1oxxxxx.o1lxxxxx": "6–10 juillet", "q1oxxxxx.o1mxxxxx": "13–17 juillet", "q1oxxxxx.o1nxxxxx": "20–24 juillet"}}'::jsonb) where form_id = 6;
update forms set draft = jsonb_set(jsonb_set(draft, '{language}', '"en"'), '{alt}', '{"language": "fr", "texts": {"title": "Notre nouvel atelier — votre avis", "intro": "Trois questions, une minute. Cela nous aide à prévoir les prochains changements.", "q30xxxxx": "Comment trouvez-vous le nouvel atelier ?", "q30xxxxx.c35xxxxx": "Mauvais", "q30xxxxx.c36xxxxx": "Moyen", "q30xxxxx.c37xxxxx": "Bien", "q30xxxxx.c38xxxxx": "Excellent", "q30xxxxx.r31xxxxx": "La lumière", "q30xxxxx.r32xxxxx": "Le bruit", "q30xxxxx.r33xxxxx": "La place à l’établi", "q30xxxxx.r34xxxxx": "Les outils à portée de main", "q40xxxxx": "Que devrions-nous améliorer en premier ?", "q40xxxxx.i41xxxxx": "Des établis plus grands", "q40xxxxx.i42xxxxx": "Une salle de finition plus calme", "q40xxxxx.i43xxxxx": "Une meilleure lumière", "q40xxxxx.i44xxxxx": "Un coin café", "q45xxxxx": "Autre chose ?"}}'::jsonb) where id = 7;
update versions set definition = jsonb_set(jsonb_set(definition, '{language}', '"en"'), '{alt}', '{"language": "fr", "texts": {"title": "Notre nouvel atelier — votre avis", "intro": "Trois questions, une minute. Cela nous aide à prévoir les prochains changements.", "q30xxxxx": "Comment trouvez-vous le nouvel atelier ?", "q30xxxxx.c35xxxxx": "Mauvais", "q30xxxxx.c36xxxxx": "Moyen", "q30xxxxx.c37xxxxx": "Bien", "q30xxxxx.c38xxxxx": "Excellent", "q30xxxxx.r31xxxxx": "La lumière", "q30xxxxx.r32xxxxx": "Le bruit", "q30xxxxx.r33xxxxx": "La place à l’établi", "q30xxxxx.r34xxxxx": "Les outils à portée de main", "q40xxxxx": "Que devrions-nous améliorer en premier ?", "q40xxxxx.i41xxxxx": "Des établis plus grands", "q40xxxxx.i42xxxxx": "Une salle de finition plus calme", "q40xxxxx.i43xxxxx": "Une meilleure lumière", "q40xxxxx.i44xxxxx": "Un coin café", "q45xxxxx": "Autre chose ?"}}'::jsonb) where form_id = 7;

-- The contact form also makes a contact in Clients and opens a ticket in
-- Support (lib/routes.ts): which question gives what.
update forms set routes = '{"contact": {"name": "q1bxxxxx", "email": "q1cxxxxx", "phone": "q1dxxxxx", "company": null, "message": "q1ixxxxx"}, "request": {"subject": "q1hxxxxx", "details": "q1ixxxxx", "email": "q1cxxxxx", "name": "q1bxxxxx"}}'::jsonb where id = 5;

select setval(pg_get_serial_sequence('forms', 'id'), 100);

-- Round 3: where answers went (answers.sent) and a web address of the
-- feedback form (form_hooks; the harness's fake Chest does not know this
-- target, so Settings shows it as the tool recorded it).
update answers set sent = '{webhooks,copy}' where id = 'seed00000000000s';
insert into form_hooks (id, form_id, kind, label, shown, created_by, created_at) values
  ('whk_seedaaaaaaaaaaaaaaaaaaaaaa', 1, 'slack', 'Customer care channel', 'https://hooks.slack.com/services/T0001/…', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '20 days');
