// Generated by scripts/fetch-fonts.mjs — do not edit by hand. The fonts of
// the theme catalogue: Fontsource packages 5.3.0, latin and latin-ext
// subsets, WOFF2 only; the files and each licence are in fonts/ of the kit's
// repository (served to tools by the Chest, not shipped in the npm package).
import type { FontEntry } from "./fonts.js";

export const fontEntries: readonly FontEntry[] = [
  {
    "id": "albert-sans",
    "family": "Albert Sans Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/albert-sans@5.3.0",
    "files": [
      {
        "file": "albert-sans-latin-ext-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "albert-sans-latin-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "atkinson-hyperlegible",
    "family": "Atkinson Hyperlegible",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource/atkinson-hyperlegible@5.3.0",
    "files": [
      {
        "file": "atkinson-hyperlegible-latin-400-italic.woff2",
        "weight": "400",
        "style": "italic",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "atkinson-hyperlegible-latin-400-normal.woff2",
        "weight": "400",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "atkinson-hyperlegible-latin-700-italic.woff2",
        "weight": "700",
        "style": "italic",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "atkinson-hyperlegible-latin-700-normal.woff2",
        "weight": "700",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "atkinson-hyperlegible-latin-ext-400-italic.woff2",
        "weight": "400",
        "style": "italic",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "atkinson-hyperlegible-latin-ext-400-normal.woff2",
        "weight": "400",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "atkinson-hyperlegible-latin-ext-700-italic.woff2",
        "weight": "700",
        "style": "italic",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "atkinson-hyperlegible-latin-ext-700-normal.woff2",
        "weight": "700",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ]
  },
  {
    "id": "barlow-semi-condensed",
    "family": "Barlow Semi Condensed",
    "category": "condensed",
    "fallback": "'Arial Narrow', system-ui, sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource/barlow-semi-condensed@5.3.0",
    "files": [
      {
        "file": "barlow-semi-condensed-latin-400-normal.woff2",
        "weight": "400",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "barlow-semi-condensed-latin-600-normal.woff2",
        "weight": "600",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "barlow-semi-condensed-latin-ext-400-normal.woff2",
        "weight": "400",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "barlow-semi-condensed-latin-ext-600-normal.woff2",
        "weight": "600",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ]
  },
  {
    "id": "bricolage-grotesque",
    "family": "Bricolage Grotesque Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/bricolage-grotesque@5.3.0",
    "files": [
      {
        "file": "bricolage-grotesque-latin-ext-wght-normal.woff2",
        "weight": "200 800",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "bricolage-grotesque-latin-wght-normal.woff2",
        "weight": "200 800",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "dm-mono",
    "family": "DM Mono",
    "category": "mono",
    "fallback": "ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace",
    "licence": "OFL-1.1",
    "source": "@fontsource/dm-mono@5.3.0",
    "files": [
      {
        "file": "dm-mono-latin-400-normal.woff2",
        "weight": "400",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "dm-mono-latin-500-normal.woff2",
        "weight": "500",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "dm-mono-latin-ext-400-normal.woff2",
        "weight": "400",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "dm-mono-latin-ext-500-normal.woff2",
        "weight": "500",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ]
  },
  {
    "id": "dm-sans",
    "family": "DM Sans Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/dm-sans@5.3.0",
    "files": [
      {
        "file": "dm-sans-latin-ext-wght-normal.woff2",
        "weight": "100 1000",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "dm-sans-latin-wght-normal.woff2",
        "weight": "100 1000",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "dm-serif-display",
    "family": "DM Serif Display",
    "category": "serif",
    "fallback": "Georgia, 'Times New Roman', serif",
    "licence": "OFL-1.1",
    "source": "@fontsource/dm-serif-display@5.3.0",
    "files": [
      {
        "file": "dm-serif-display-latin-400-italic.woff2",
        "weight": "400",
        "style": "italic",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "dm-serif-display-latin-400-normal.woff2",
        "weight": "400",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "dm-serif-display-latin-ext-400-italic.woff2",
        "weight": "400",
        "style": "italic",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "dm-serif-display-latin-ext-400-normal.woff2",
        "weight": "400",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ]
  },
  {
    "id": "figtree",
    "family": "Figtree Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/figtree@5.3.0",
    "files": [
      {
        "file": "figtree-latin-ext-wght-normal.woff2",
        "weight": "300 900",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "figtree-latin-wght-normal.woff2",
        "weight": "300 900",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "fraunces",
    "family": "Fraunces Variable",
    "category": "serif",
    "fallback": "Georgia, 'Times New Roman', serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/fraunces@5.3.0",
    "files": [
      {
        "file": "fraunces-latin-ext-wght-italic.woff2",
        "weight": "100 900",
        "style": "italic",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "fraunces-latin-ext-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "fraunces-latin-wght-italic.woff2",
        "weight": "100 900",
        "style": "italic",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "fraunces-latin-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "fredoka",
    "family": "Fredoka Variable",
    "category": "rounded",
    "fallback": "ui-rounded, 'Arial Rounded MT Bold', system-ui, sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/fredoka@5.3.0",
    "files": [
      {
        "file": "fredoka-latin-ext-wght-normal.woff2",
        "weight": "300 700",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "fredoka-latin-wght-normal.woff2",
        "weight": "300 700",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "hanken-grotesk",
    "family": "Hanken Grotesk Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/hanken-grotesk@5.3.0",
    "files": [
      {
        "file": "hanken-grotesk-latin-ext-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "hanken-grotesk-latin-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "ibm-plex-mono",
    "family": "IBM Plex Mono",
    "category": "mono",
    "fallback": "ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace",
    "licence": "OFL-1.1",
    "source": "@fontsource/ibm-plex-mono@5.3.0",
    "files": [
      {
        "file": "ibm-plex-mono-latin-400-normal.woff2",
        "weight": "400",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "ibm-plex-mono-latin-500-normal.woff2",
        "weight": "500",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "ibm-plex-mono-latin-600-normal.woff2",
        "weight": "600",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "ibm-plex-mono-latin-ext-400-normal.woff2",
        "weight": "400",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "ibm-plex-mono-latin-ext-500-normal.woff2",
        "weight": "500",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "ibm-plex-mono-latin-ext-600-normal.woff2",
        "weight": "600",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ]
  },
  {
    "id": "ibm-plex-sans",
    "family": "IBM Plex Sans Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/ibm-plex-sans@5.3.0",
    "files": [
      {
        "file": "ibm-plex-sans-latin-ext-wght-normal.woff2",
        "weight": "100 700",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "ibm-plex-sans-latin-wght-normal.woff2",
        "weight": "100 700",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "instrument-sans",
    "family": "Instrument Sans Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/instrument-sans@5.3.0",
    "files": [
      {
        "file": "instrument-sans-latin-ext-wght-normal.woff2",
        "weight": "400 700",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "instrument-sans-latin-wght-normal.woff2",
        "weight": "400 700",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "inter",
    "family": "Inter Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/inter@5.3.0",
    "files": [
      {
        "file": "inter-latin-ext-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "inter-latin-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "jetbrains-mono",
    "family": "JetBrains Mono Variable",
    "category": "mono",
    "fallback": "ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/jetbrains-mono@5.3.0",
    "files": [
      {
        "file": "jetbrains-mono-latin-ext-wght-normal.woff2",
        "weight": "100 800",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "jetbrains-mono-latin-wght-normal.woff2",
        "weight": "100 800",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "libre-caslon-text",
    "family": "Libre Caslon Text",
    "category": "serif",
    "fallback": "'Iowan Old Style', Georgia, serif",
    "licence": "OFL-1.1",
    "source": "@fontsource/libre-caslon-text@5.3.0",
    "files": [
      {
        "file": "libre-caslon-text-latin-400-italic.woff2",
        "weight": "400",
        "style": "italic",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "libre-caslon-text-latin-400-normal.woff2",
        "weight": "400",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "libre-caslon-text-latin-700-normal.woff2",
        "weight": "700",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "libre-caslon-text-latin-ext-400-italic.woff2",
        "weight": "400",
        "style": "italic",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "libre-caslon-text-latin-ext-400-normal.woff2",
        "weight": "400",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "libre-caslon-text-latin-ext-700-normal.woff2",
        "weight": "700",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ]
  },
  {
    "id": "libre-franklin",
    "family": "Libre Franklin Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/libre-franklin@5.3.0",
    "files": [
      {
        "file": "libre-franklin-latin-ext-wght-italic.woff2",
        "weight": "100 900",
        "style": "italic",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "libre-franklin-latin-ext-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "libre-franklin-latin-wght-italic.woff2",
        "weight": "100 900",
        "style": "italic",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "libre-franklin-latin-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "manrope",
    "family": "Manrope Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/manrope@5.3.0",
    "files": [
      {
        "file": "manrope-latin-ext-wght-normal.woff2",
        "weight": "200 800",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "manrope-latin-wght-normal.woff2",
        "weight": "200 800",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "martian-mono",
    "family": "Martian Mono Variable",
    "category": "mono",
    "fallback": "ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/martian-mono@5.3.0",
    "files": [
      {
        "file": "martian-mono-latin-ext-wght-normal.woff2",
        "weight": "100 800",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "martian-mono-latin-wght-normal.woff2",
        "weight": "100 800",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "newsreader",
    "family": "Newsreader Variable",
    "category": "serif",
    "fallback": "'Iowan Old Style', Georgia, 'Times New Roman', serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/newsreader@5.3.0",
    "files": [
      {
        "file": "newsreader-latin-ext-wght-italic.woff2",
        "weight": "200 800",
        "style": "italic",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "newsreader-latin-ext-wght-normal.woff2",
        "weight": "200 800",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "newsreader-latin-wght-italic.woff2",
        "weight": "200 800",
        "style": "italic",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "newsreader-latin-wght-normal.woff2",
        "weight": "200 800",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "nunito",
    "family": "Nunito Variable",
    "category": "rounded",
    "fallback": "ui-rounded, system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/nunito@5.3.0",
    "files": [
      {
        "file": "nunito-latin-ext-wght-normal.woff2",
        "weight": "200 1000",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "nunito-latin-wght-normal.woff2",
        "weight": "200 1000",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "nunito-sans",
    "family": "Nunito Sans Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/nunito-sans@5.3.0",
    "files": [
      {
        "file": "nunito-sans-latin-ext-wght-normal.woff2",
        "weight": "200 1000",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "nunito-sans-latin-wght-normal.woff2",
        "weight": "200 1000",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "outfit",
    "family": "Outfit Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/outfit@5.3.0",
    "files": [
      {
        "file": "outfit-latin-ext-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "outfit-latin-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "plus-jakarta-sans",
    "family": "Plus Jakarta Sans Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/plus-jakarta-sans@5.3.0",
    "files": [
      {
        "file": "plus-jakarta-sans-latin-ext-wght-normal.woff2",
        "weight": "200 800",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "plus-jakarta-sans-latin-wght-normal.woff2",
        "weight": "200 800",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "public-sans",
    "family": "Public Sans Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/public-sans@5.3.0",
    "files": [
      {
        "file": "public-sans-latin-ext-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "public-sans-latin-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "red-hat-mono",
    "family": "Red Hat Mono Variable",
    "category": "mono",
    "fallback": "ui-monospace, 'SF Mono', Menlo, monospace",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/red-hat-mono@5.3.0",
    "files": [
      {
        "file": "red-hat-mono-latin-ext-wght-normal.woff2",
        "weight": "300 700",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "red-hat-mono-latin-wght-normal.woff2",
        "weight": "300 700",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "red-hat-text",
    "family": "Red Hat Text Variable",
    "category": "sans",
    "fallback": "'Segoe UI', system-ui, sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/red-hat-text@5.3.0",
    "files": [
      {
        "file": "red-hat-text-latin-ext-wght-normal.woff2",
        "weight": "300 700",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "red-hat-text-latin-wght-normal.woff2",
        "weight": "300 700",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "source-sans-3",
    "family": "Source Sans 3 Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/source-sans-3@5.3.0",
    "files": [
      {
        "file": "source-sans-3-latin-ext-wght-normal.woff2",
        "weight": "200 900",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "source-sans-3-latin-wght-normal.woff2",
        "weight": "200 900",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "space-grotesk",
    "family": "Space Grotesk Variable",
    "category": "sans",
    "fallback": "system-ui, sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/space-grotesk@5.3.0",
    "files": [
      {
        "file": "space-grotesk-latin-ext-wght-normal.woff2",
        "weight": "300 700",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "space-grotesk-latin-wght-normal.woff2",
        "weight": "300 700",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "work-sans",
    "family": "Work Sans Variable",
    "category": "sans",
    "fallback": "system-ui, -apple-system, 'Segoe UI', sans-serif",
    "licence": "OFL-1.1",
    "source": "@fontsource-variable/work-sans@5.3.0",
    "files": [
      {
        "file": "work-sans-latin-ext-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      },
      {
        "file": "work-sans-latin-wght-normal.woff2",
        "weight": "100 900",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      }
    ]
  },
  {
    "id": "young-serif",
    "family": "Young Serif",
    "category": "serif",
    "fallback": "Georgia, 'Times New Roman', serif",
    "licence": "OFL-1.1",
    "source": "@fontsource/young-serif@5.3.0",
    "files": [
      {
        "file": "young-serif-latin-400-normal.woff2",
        "weight": "400",
        "style": "normal",
        "subset": "latin",
        "range": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
      },
      {
        "file": "young-serif-latin-ext-400-normal.woff2",
        "weight": "400",
        "style": "normal",
        "subset": "latin-ext",
        "range": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
      }
    ]
  }
];
