-- Sample data for local runs and screenshots (never run by the Chest): a
-- small Lyon design studio, "Atelier Martin SARL", its clients, catalogue,
-- quotes in every state, invoices (paid, partly paid, overdue) and a credit
-- note. The SIREN, SIRET, VAT numbers and IBAN are fictitious (valid by their
-- keys only); any match with a real company is a coincidence. Dates are
-- relative to the day it is loaded, numbers use that day's year. Generated
-- from a description (totals by lib/totals.ts); member ids are the dev
-- harness's (lab/chest-dev/cast.mjs).
do $$
declare
  t date := current_date;
  y text := to_char(current_date, 'YYYY');
  doc bigint;
begin
update company set legal_name = 'Atelier Martin SARL', trade_name = 'Atelier Martin', legal_form = 'SARL', capital = 1000000,
  address = '12 rue des Tanneurs', postcode = '69002', city = 'Lyon', siren = '853128940', siret = '85312894000014', rcs_city = 'Lyon',
  vat_number = 'FR25853128940', email = 'bonjour@atelier-martin.test', phone = '04 78 42 18 90', website = 'atelier-martin.test', bank = 'Banque Populaire', iban = 'FR76 3000 6000 0112 3456 7890 189',
  bic = 'AGRIFRPP', footer = 'Assurance responsabilité civile professionnelle : Hiscox, contrat n° HX-2291-778, couverture France et Union européenne.', updated_by = 'mbr_camilleaaaaaaaaaaaaaaaaaaa', updated_at = now() where id = 1;
insert into clients (kind, name, contact, email, phone, address, postcode, city, country, delivery_address, siren, vat_number, language, reverse_charge, notes, created_by) values ('company', 'Boulangerie Dupain SAS', 'Marie Dupain', 'marie@dupain.test', '04 78 37 12 40', '3 place Bellecour', '69002', 'Lyon', 'FR', '', '812345676', 'FR19812345676', 'fr', false, 'Préfère être appelée le matin, avant 10 h.', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa');
insert into clients (kind, name, contact, email, phone, address, postcode, city, country, delivery_address, siren, vat_number, language, reverse_charge, notes, created_by) values ('company', 'Garage Rossi SARL', 'Luca Rossi', 'compta@garage-rossi.test', '04 72 70 55 18', '45 avenue Jean Jaurès', '69007', 'Lyon', 'FR', '', '412873564', 'FR59412873564', 'fr', false, '', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa');
insert into clients (kind, name, contact, email, phone, address, postcode, city, country, delivery_address, siren, vat_number, language, reverse_charge, notes, created_by) values ('company', 'Cabinet Lefort Avocats', 'Hélène Lefort', 'secretariat@lefort-avocats.test', '04 78 92 60 00', '8 quai Saint-Antoine
3e étage', '69002', 'Lyon', 'FR', '', '904123452', 'FR11904123452', 'fr', false, 'Factures à envoyer au secrétariat.', 'mbr_camilleaaaaaaaaaaaaaaaaaaa');
insert into clients (kind, name, contact, email, phone, address, postcode, city, country, delivery_address, siren, vat_number, language, reverse_charge, notes, created_by) values ('company', 'Studio Verbeke BV', 'Pieter Verbeke', 'finance@verbeke.test', '+32 2 511 42 00', 'Rue Antoine Dansaert 92', '1000', 'Bruxelles', 'BE', '', '', 'BE0765432146', 'en', true, 'English documents, reverse charge (EU company).', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa');
insert into clients (kind, name, contact, email, phone, address, postcode, city, country, delivery_address, siren, vat_number, language, reverse_charge, notes, created_by) values ('company', 'Association Les Jardins du Rhône', 'Paul Girard', 'tresorerie@jardins-rhone.test', '', '17 rue de la Soie', '69100', 'Villeurbanne', 'FR', 'Local associatif
4 rue des Maraîchers
69100 Villeurbanne', '882314578', '', 'fr', false, '', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa');
insert into clients (kind, name, contact, email, phone, address, postcode, city, country, delivery_address, siren, vat_number, language, reverse_charge, notes, created_by) values ('person', 'Jeanne Roux', '', 'jeanne.roux@example.test', '06 12 34 56 78', '5 impasse des Lilas', '69300', 'Caluire-et-Cuire', 'FR', '', '', '', 'fr', false, '', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa');
insert into items (name, description, unit, unit_price, vat_rate, goods, created_by) values ('Journée de design', 'Direction artistique et mise en page, par l’équipe.', 'jour', 65000, 2000, false, 'mbr_camilleaaaaaaaaaaaaaaaaaaa');
insert into items (name, description, unit, unit_price, vat_rate, goods, created_by) values ('Atelier de cadrage', 'Une demi-journée avec vos équipes : objectifs, publics, contenus.', 'forfait', 38000, 2000, false, 'mbr_camilleaaaaaaaaaaaaaaaaaaa');
insert into items (name, description, unit, unit_price, vat_rate, goods, created_by) values ('Maquette de page', 'Une page, deux allers-retours inclus.', 'page', 42000, 2000, false, 'mbr_camilleaaaaaaaaaaaaaaaaaaa');
insert into items (name, description, unit, unit_price, vat_rate, goods, created_by) values ('Développement web', 'Intégration et développement du site.', 'jour', 60000, 2000, false, 'mbr_camilleaaaaaaaaaaaaaaaaaaa');
insert into items (name, description, unit, unit_price, vat_rate, goods, created_by) values ('Identité visuelle', 'Logo, couleurs, typographies et guide d’usage.', 'forfait', 240000, 2000, false, 'mbr_camilleaaaaaaaaaaaaaaaaaaa');
insert into items (name, description, unit, unit_price, vat_rate, goods, created_by) values ('Logo', 'Trois pistes, une finalisée.', 'forfait', 90000, 2000, false, 'mbr_camilleaaaaaaaaaaaaaaaaaaa');
insert into items (name, description, unit, unit_price, vat_rate, goods, created_by) values ('Hébergement annuel', 'Serveur en France, sauvegardes quotidiennes.', 'an', 24000, 2000, false, 'mbr_camilleaaaaaaaaaaaaaaaaaaa');
insert into items (name, description, unit, unit_price, vat_rate, goods, created_by) values ('Maintenance', 'Mises à jour et petites corrections.', 'mois', 9000, 2000, false, 'mbr_camilleaaaaaaaaaaaaaaaaaaa');
insert into items (name, description, unit, unit_price, vat_rate, goods, created_by) values ('Nom de domaine', '', 'an', 1800, 2000, false, 'mbr_camilleaaaaaaaaaaaaaaaaaaa');
insert into items (name, description, unit, unit_price, vat_rate, goods, created_by) values ('Cartes de visite', 'Impression offset, 350 g, lot de 500.', 'lot', 8500, 2000, true, 'mbr_camilleaaaaaaaaaaaaaaaaaaa');
insert into items (name, description, unit, unit_price, vat_rate, goods, created_by) values ('Petit manuel de typographie', 'Livre, 128 pages.', 'exemplaire', 2400, 550, true, 'mbr_camilleaaaaaaaaaaaaaaaaaaa');
insert into items (name, description, unit, unit_price, vat_rate, goods, created_by) values ('Formation Canva', 'Une demi-journée pour trois personnes, dans vos locaux.', 'forfait', 45000, 2000, false, 'mbr_camilleaaaaaaaaaaaaaaaaaaa');
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('quote', 'draft', 1, 'Refonte du site vitrine', 'fr', 'EUR', 30, 'standard', 'Démarrage possible sous deux semaines après accord.', null, null, null, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', (t - 72) + time '10:30', (t - 72) + time '10:30', t - 70 + 30, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'section', null, 'Conception', 0, '', 0, 0, 0, false, 0);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 2, 'line', 2, 'Atelier de cadrage
Une demi-journée avec vos équipes : objectifs, publics, contenus.', 1000, 'forfait', 38000, 0, 2000, false, 38000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 3, 'line', 3, 'Maquette de page
Une page, deux allers-retours inclus.', 4000, 'page', 42000, 0, 2000, false, 168000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 4, 'section', null, 'Réalisation', 0, '', 0, 0, 0, false, 0);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 5, 'line', 4, 'Développement web
Intégration et développement du site.', 5000, 'jour', 60000, 0, 2000, false, 300000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 6, 'line', 7, 'Hébergement annuel
Serveur en France, sauvegardes quotidiennes.', 1000, 'an', 24000, 0, 2000, false, 24000);
update documents set net = 530000, vat = 106000, gross = 636000, rates = '[{"rate":2000,"base":530000,"vat":106000}]'::jsonb, status = 'accepted', number = 'D-'||y||'-0001', year = to_char(current_date, 'YYYY')::int, seq = 1, issue_date = t - 70, seller = '{"legalName":"Atelier Martin SARL","tradeName":"Atelier Martin","legalForm":"SARL","capital":1000000,"address":"12 rue des Tanneurs","postcode":"69002","city":"Lyon","country":"FR","siren":"853128940","siret":"85312894000014","rcsCity":"Lyon","vatNumber":"FR25853128940","franchise":false,"vatOnDebits":false,"email":"bonjour@atelier-martin.test","phone":"04 78 42 18 90","website":"atelier-martin.test","bank":"Banque Populaire","iban":"FR76 3000 6000 0112 3456 7890 189","bic":"AGRIFRPP","logo":null,"logoType":null,"paymentDays":30,"penaltyRate":null,"earlyDiscount":"","footer":"Assurance responsabilité civile professionnelle : Hiscox, contrat n° HX-2291-778, couverture France et Union européenne."}'::jsonb, buyer = '{"kind":"company","name":"Boulangerie Dupain SAS","contact":"Marie Dupain","email":"marie@dupain.test","address":"3 place Bellecour","postcode":"69002","city":"Lyon","country":"FR","deliveryAddress":"","siren":"812345676","vatNumber":"FR19812345676"}'::jsonb, sent_at = (t - 70) + time '10:30', sent_by = 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', emailed_to = 'marie@dupain.test', decided_at = (t - 64) + time '10:30', decided_by = 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa' where id = doc;
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('quote', 'draft', 2, 'Nouveau logo', 'fr', 'EUR', 30, 'standard', '', null, null, null, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', (t - 60) + time '10:30', (t - 60) + time '10:30', t - 58 + 30, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'line', 6, 'Logo
Trois pistes, une finalisée.', 1000, 'forfait', 90000, 0, 2000, false, 90000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 2, 'line', 10, 'Cartes de visite
Impression offset, 350 g, lot de 500.', 2000, 'lot', 8500, 0, 2000, true, 17000);
update documents set net = 107000, vat = 21400, gross = 128400, rates = '[{"rate":2000,"base":107000,"vat":21400}]'::jsonb, status = 'accepted', number = 'D-'||y||'-0002', year = to_char(current_date, 'YYYY')::int, seq = 2, issue_date = t - 58, seller = '{"legalName":"Atelier Martin SARL","tradeName":"Atelier Martin","legalForm":"SARL","capital":1000000,"address":"12 rue des Tanneurs","postcode":"69002","city":"Lyon","country":"FR","siren":"853128940","siret":"85312894000014","rcsCity":"Lyon","vatNumber":"FR25853128940","franchise":false,"vatOnDebits":false,"email":"bonjour@atelier-martin.test","phone":"04 78 42 18 90","website":"atelier-martin.test","bank":"Banque Populaire","iban":"FR76 3000 6000 0112 3456 7890 189","bic":"AGRIFRPP","logo":null,"logoType":null,"paymentDays":30,"penaltyRate":null,"earlyDiscount":"","footer":"Assurance responsabilité civile professionnelle : Hiscox, contrat n° HX-2291-778, couverture France et Union européenne."}'::jsonb, buyer = '{"kind":"company","name":"Garage Rossi SARL","contact":"Luca Rossi","email":"compta@garage-rossi.test","address":"45 avenue Jean Jaurès","postcode":"69007","city":"Lyon","country":"FR","deliveryAddress":"","siren":"412873564","vatNumber":"FR59412873564"}'::jsonb, sent_at = (t - 58) + time '10:30', sent_by = 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', emailed_to = 'compta@garage-rossi.test', decided_at = (t - 55) + time '10:30', decided_by = 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa' where id = doc;
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('quote', 'draft', 3, 'Identité visuelle complète', 'fr', 'EUR', 30, 'standard', '', null, null, null, 'mbr_camilleaaaaaaaaaaaaaaaaaaa', (t - 50) + time '10:30', (t - 50) + time '10:30', t - 49 + 30, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'line', 5, 'Identité visuelle
Logo, couleurs, typographies et guide d’usage.', 1000, 'forfait', 240000, 0, 2000, false, 240000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 2, 'line', 1, 'Journée de design
Direction artistique et mise en page, par l’équipe.', 2000, 'jour', 65000, 0, 2000, false, 130000);
update documents set net = 370000, vat = 74000, gross = 444000, rates = '[{"rate":2000,"base":370000,"vat":74000}]'::jsonb, status = 'refused', number = 'D-'||y||'-0003', year = to_char(current_date, 'YYYY')::int, seq = 3, issue_date = t - 49, seller = '{"legalName":"Atelier Martin SARL","tradeName":"Atelier Martin","legalForm":"SARL","capital":1000000,"address":"12 rue des Tanneurs","postcode":"69002","city":"Lyon","country":"FR","siren":"853128940","siret":"85312894000014","rcsCity":"Lyon","vatNumber":"FR25853128940","franchise":false,"vatOnDebits":false,"email":"bonjour@atelier-martin.test","phone":"04 78 42 18 90","website":"atelier-martin.test","bank":"Banque Populaire","iban":"FR76 3000 6000 0112 3456 7890 189","bic":"AGRIFRPP","logo":null,"logoType":null,"paymentDays":30,"penaltyRate":null,"earlyDiscount":"","footer":"Assurance responsabilité civile professionnelle : Hiscox, contrat n° HX-2291-778, couverture France et Union européenne."}'::jsonb, buyer = '{"kind":"company","name":"Cabinet Lefort Avocats","contact":"Hélène Lefort","email":"secretariat@lefort-avocats.test","address":"8 quai Saint-Antoine\n3e étage","postcode":"69002","city":"Lyon","country":"FR","deliveryAddress":"","siren":"904123452","vatNumber":"FR11904123452"}'::jsonb, sent_at = (t - 49) + time '10:30', sent_by = 'mbr_camilleaaaaaaaaaaaaaaaaaaa', emailed_to = 'secretariat@lefort-avocats.test', decided_at = (t - 40) + time '10:30', decided_by = 'mbr_camilleaaaaaaaaaaaaaaaaaaa' where id = doc;
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('quote', 'draft', 5, 'Affiches de la fête des jardins', 'fr', 'EUR', 30, 'standard', '', null, null, null, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', (t - 45) + time '10:30', (t - 45) + time '10:30', t - 44 + 30, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'line', 1, 'Journée de design
Direction artistique et mise en page, par l’équipe.', 1500, 'jour', 65000, 0, 2000, false, 97500);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 2, 'line', null, 'Impression de 50 affiches A2', 50000, 'affiche', 480, 0, 2000, true, 24000);
update documents set net = 121500, vat = 24300, gross = 145800, rates = '[{"rate":2000,"base":121500,"vat":24300}]'::jsonb, status = 'sent', number = 'D-'||y||'-0004', year = to_char(current_date, 'YYYY')::int, seq = 4, issue_date = t - 44, seller = '{"legalName":"Atelier Martin SARL","tradeName":"Atelier Martin","legalForm":"SARL","capital":1000000,"address":"12 rue des Tanneurs","postcode":"69002","city":"Lyon","country":"FR","siren":"853128940","siret":"85312894000014","rcsCity":"Lyon","vatNumber":"FR25853128940","franchise":false,"vatOnDebits":false,"email":"bonjour@atelier-martin.test","phone":"04 78 42 18 90","website":"atelier-martin.test","bank":"Banque Populaire","iban":"FR76 3000 6000 0112 3456 7890 189","bic":"AGRIFRPP","logo":null,"logoType":null,"paymentDays":30,"penaltyRate":null,"earlyDiscount":"","footer":"Assurance responsabilité civile professionnelle : Hiscox, contrat n° HX-2291-778, couverture France et Union européenne."}'::jsonb, buyer = '{"kind":"company","name":"Association Les Jardins du Rhône","contact":"Paul Girard","email":"tresorerie@jardins-rhone.test","address":"17 rue de la Soie","postcode":"69100","city":"Villeurbanne","country":"FR","deliveryAddress":"Local associatif\n4 rue des Maraîchers\n69100 Villeurbanne","siren":"882314578","vatNumber":""}'::jsonb, sent_at = (t - 44) + time '10:30', sent_by = 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', emailed_to = 'tresorerie@jardins-rhone.test' where id = doc;
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('quote', 'draft', 4, 'Website redesign — phase 1', 'en', 'EUR', 30, 'reverse_charge', '', null, null, null, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', (t - 26) + time '10:30', (t - 26) + time '10:30', t - 25 + 30, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'line', null, 'Discovery workshop', 1000, 'day', 65000, 0, 2000, false, 65000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 2, 'line', null, 'Page mock-ups', 6000, 'page', 42000, 1000, 2000, false, 226800);
update documents set net = 291800, vat = 0, gross = 291800, rates = '[{"rate":0,"base":291800,"vat":0}]'::jsonb, status = 'accepted', number = 'D-'||y||'-0005', year = to_char(current_date, 'YYYY')::int, seq = 5, issue_date = t - 25, seller = '{"legalName":"Atelier Martin SARL","tradeName":"Atelier Martin","legalForm":"SARL","capital":1000000,"address":"12 rue des Tanneurs","postcode":"69002","city":"Lyon","country":"FR","siren":"853128940","siret":"85312894000014","rcsCity":"Lyon","vatNumber":"FR25853128940","franchise":false,"vatOnDebits":false,"email":"bonjour@atelier-martin.test","phone":"04 78 42 18 90","website":"atelier-martin.test","bank":"Banque Populaire","iban":"FR76 3000 6000 0112 3456 7890 189","bic":"AGRIFRPP","logo":null,"logoType":null,"paymentDays":30,"penaltyRate":null,"earlyDiscount":"","footer":"Assurance responsabilité civile professionnelle : Hiscox, contrat n° HX-2291-778, couverture France et Union européenne."}'::jsonb, buyer = '{"kind":"company","name":"Studio Verbeke BV","contact":"Pieter Verbeke","email":"finance@verbeke.test","address":"Rue Antoine Dansaert 92","postcode":"1000","city":"Bruxelles","country":"BE","deliveryAddress":"","siren":"","vatNumber":"BE0765432146"}'::jsonb, sent_at = (t - 25) + time '10:30', sent_by = 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', emailed_to = 'finance@verbeke.test', decided_at = (t - 20) + time '10:30', decided_by = 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa' where id = doc;
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('quote', 'draft', 6, 'Faire-part de mariage', 'fr', 'EUR', 30, 'standard', '', null, null, null, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', (t - 12) + time '10:30', (t - 12) + time '10:30', t - 11 + 15, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'line', 1, 'Journée de design
Direction artistique et mise en page, par l’équipe.', 1000, 'jour', 65000, 0, 2000, false, 65000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 2, 'line', null, 'Impression de 120 faire-part, papier coton', 120000, '', 350, 0, 2000, true, 42000);
update documents set net = 107000, vat = 21400, gross = 128400, rates = '[{"rate":2000,"base":107000,"vat":21400}]'::jsonb, status = 'sent', number = 'D-'||y||'-0006', year = to_char(current_date, 'YYYY')::int, seq = 6, issue_date = t - 11, seller = '{"legalName":"Atelier Martin SARL","tradeName":"Atelier Martin","legalForm":"SARL","capital":1000000,"address":"12 rue des Tanneurs","postcode":"69002","city":"Lyon","country":"FR","siren":"853128940","siret":"85312894000014","rcsCity":"Lyon","vatNumber":"FR25853128940","franchise":false,"vatOnDebits":false,"email":"bonjour@atelier-martin.test","phone":"04 78 42 18 90","website":"atelier-martin.test","bank":"Banque Populaire","iban":"FR76 3000 6000 0112 3456 7890 189","bic":"AGRIFRPP","logo":null,"logoType":null,"paymentDays":30,"penaltyRate":null,"earlyDiscount":"","footer":"Assurance responsabilité civile professionnelle : Hiscox, contrat n° HX-2291-778, couverture France et Union européenne."}'::jsonb, buyer = '{"kind":"person","name":"Jeanne Roux","contact":"","email":"jeanne.roux@example.test","address":"5 impasse des Lilas","postcode":"69300","city":"Caluire-et-Cuire","country":"FR","deliveryAddress":"","siren":"","vatNumber":""}'::jsonb, sent_at = (t - 11) + time '10:30', sent_by = 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', emailed_to = 'jeanne.roux@example.test' where id = doc;
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('quote', 'draft', 3, 'Site du cabinet — refonte', 'fr', 'EUR', 30, 'standard', '', null, null, null, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', (t - 3) + time '10:30', (t - 3) + time '10:30', t + 30, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'section', null, 'Conception', 0, '', 0, 0, 0, false, 0);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 2, 'line', 2, 'Atelier de cadrage
Une demi-journée avec vos équipes : objectifs, publics, contenus.', 1000, 'forfait', 38000, 0, 2000, false, 38000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 3, 'line', 3, 'Maquette de page
Une page, deux allers-retours inclus.', 5000, 'page', 42000, 0, 2000, false, 210000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 4, 'section', null, 'Réalisation', 0, '', 0, 0, 0, false, 0);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 5, 'line', 4, 'Développement web
Intégration et développement du site.', 8000, 'jour', 60000, 0, 2000, false, 480000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 6, 'line', 8, 'Maintenance
Mises à jour et petites corrections.', 12000, 'mois', 9000, 0, 2000, false, 108000);
update documents set net = 836000, vat = 167200, gross = 1003200, rates = '[{"rate":2000,"base":836000,"vat":167200}]'::jsonb where id = doc;
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('quote', 'draft', 5, 'Formation aux outils de communication', 'fr', 'EUR', 30, 'standard', '', null, null, null, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', (t - 1) + time '10:30', (t - 1) + time '10:30', t + 30, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'line', 12, 'Formation Canva
Une demi-journée pour trois personnes, dans vos locaux.', 2000, 'forfait', 45000, 0, 2000, false, 90000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 2, 'line', 11, 'Petit manuel de typographie
Livre, 128 pages.', 3000, 'exemplaire', 2400, 0, 550, true, 7200);
update documents set net = 97200, vat = 18396, gross = 115596, rates = '[{"rate":2000,"base":90000,"vat":18000},{"rate":550,"base":7200,"vat":396}]'::jsonb where id = doc;
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('invoice', 'draft', 1, 'Refonte du site vitrine', 'fr', 'EUR', 30, 'standard', '', 1, 3000, null, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', (t - 63) + time '10:30', (t - 63) + time '10:30', null, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'line', null, replace('Acompte de 30 % sur le devis D-{Y}-0001', '{Y}', y), 1000, '', 159000, 0, 2000, false, 159000);
update documents set net = 159000, vat = 31800, gross = 190800, rates = '[{"rate":2000,"base":159000,"vat":31800}]'::jsonb, status = 'final', number = 'F-'||y||'-0001', year = to_char(current_date, 'YYYY')::int, seq = 1, issue_date = t - 63, seller = '{"legalName":"Atelier Martin SARL","tradeName":"Atelier Martin","legalForm":"SARL","capital":1000000,"address":"12 rue des Tanneurs","postcode":"69002","city":"Lyon","country":"FR","siren":"853128940","siret":"85312894000014","rcsCity":"Lyon","vatNumber":"FR25853128940","franchise":false,"vatOnDebits":false,"email":"bonjour@atelier-martin.test","phone":"04 78 42 18 90","website":"atelier-martin.test","bank":"Banque Populaire","iban":"FR76 3000 6000 0112 3456 7890 189","bic":"AGRIFRPP","logo":null,"logoType":null,"paymentDays":30,"penaltyRate":null,"earlyDiscount":"","footer":"Assurance responsabilité civile professionnelle : Hiscox, contrat n° HX-2291-778, couverture France et Union européenne."}'::jsonb, buyer = '{"kind":"company","name":"Boulangerie Dupain SAS","contact":"Marie Dupain","email":"marie@dupain.test","address":"3 place Bellecour","postcode":"69002","city":"Lyon","country":"FR","deliveryAddress":"","siren":"812345676","vatNumber":"FR19812345676"}'::jsonb, due_date = t - 63 + 30, finalised_at = (t - 63) + time '10:30', finalised_by = 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', sent_at = (t - 63) + time '10:30', sent_by = 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', emailed_to = 'marie@dupain.test' where id = doc;
insert into payments (document_id, paid_on, amount, method, note, created_by, created_at) values (doc, t - 55, 190800, 'transfer', 'VIR DUPAIN SAS', 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', (t - 55) + time '10:30');
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('invoice', 'draft', 2, 'Nouveau logo', 'fr', 'EUR', 30, 'standard', '', 2, null, null, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', (t - 50) + time '10:30', (t - 50) + time '10:30', null, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'line', 6, 'Logo
Trois pistes, une finalisée.', 1000, 'forfait', 90000, 0, 2000, false, 90000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 2, 'line', 10, 'Cartes de visite
Impression offset, 350 g, lot de 500.', 2000, 'lot', 8500, 0, 2000, true, 17000);
update documents set net = 107000, vat = 21400, gross = 128400, rates = '[{"rate":2000,"base":107000,"vat":21400}]'::jsonb, status = 'final', number = 'F-'||y||'-0002', year = to_char(current_date, 'YYYY')::int, seq = 2, issue_date = t - 48, seller = '{"legalName":"Atelier Martin SARL","tradeName":"Atelier Martin","legalForm":"SARL","capital":1000000,"address":"12 rue des Tanneurs","postcode":"69002","city":"Lyon","country":"FR","siren":"853128940","siret":"85312894000014","rcsCity":"Lyon","vatNumber":"FR25853128940","franchise":false,"vatOnDebits":false,"email":"bonjour@atelier-martin.test","phone":"04 78 42 18 90","website":"atelier-martin.test","bank":"Banque Populaire","iban":"FR76 3000 6000 0112 3456 7890 189","bic":"AGRIFRPP","logo":null,"logoType":null,"paymentDays":30,"penaltyRate":null,"earlyDiscount":"","footer":"Assurance responsabilité civile professionnelle : Hiscox, contrat n° HX-2291-778, couverture France et Union européenne."}'::jsonb, buyer = '{"kind":"company","name":"Garage Rossi SARL","contact":"Luca Rossi","email":"compta@garage-rossi.test","address":"45 avenue Jean Jaurès","postcode":"69007","city":"Lyon","country":"FR","deliveryAddress":"","siren":"412873564","vatNumber":"FR59412873564"}'::jsonb, due_date = t - 48 + 30, finalised_at = (t - 48) + time '10:30', finalised_by = 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', sent_at = (t - 48) + time '10:30', sent_by = 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', emailed_to = 'compta@garage-rossi.test' where id = doc;
insert into payments (document_id, paid_on, amount, method, note, created_by, created_at) values (doc, t - 30, 128400, 'cheque', 'Chèque n° 4410233', 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', (t - 30) + time '10:30');
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('invoice', 'draft', 5, 'Programme de la saison', 'fr', 'EUR', 30, 'standard', '', null, null, null, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', (t - 42) + time '10:30', (t - 42) + time '10:30', null, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'line', 1, 'Journée de design
Direction artistique et mise en page, par l’équipe.', 1000, 'jour', 65000, 0, 2000, false, 65000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 2, 'line', 11, 'Petit manuel de typographie
Livre, 128 pages.', 10000, 'exemplaire', 2400, 0, 550, true, 24000);
update documents set net = 89000, vat = 14320, gross = 103320, rates = '[{"rate":2000,"base":65000,"vat":13000},{"rate":550,"base":24000,"vat":1320}]'::jsonb, status = 'final', number = 'F-'||y||'-0003', year = to_char(current_date, 'YYYY')::int, seq = 3, issue_date = t - 40, seller = '{"legalName":"Atelier Martin SARL","tradeName":"Atelier Martin","legalForm":"SARL","capital":1000000,"address":"12 rue des Tanneurs","postcode":"69002","city":"Lyon","country":"FR","siren":"853128940","siret":"85312894000014","rcsCity":"Lyon","vatNumber":"FR25853128940","franchise":false,"vatOnDebits":false,"email":"bonjour@atelier-martin.test","phone":"04 78 42 18 90","website":"atelier-martin.test","bank":"Banque Populaire","iban":"FR76 3000 6000 0112 3456 7890 189","bic":"AGRIFRPP","logo":null,"logoType":null,"paymentDays":30,"penaltyRate":null,"earlyDiscount":"","footer":"Assurance responsabilité civile professionnelle : Hiscox, contrat n° HX-2291-778, couverture France et Union européenne."}'::jsonb, buyer = '{"kind":"company","name":"Association Les Jardins du Rhône","contact":"Paul Girard","email":"tresorerie@jardins-rhone.test","address":"17 rue de la Soie","postcode":"69100","city":"Villeurbanne","country":"FR","deliveryAddress":"Local associatif\n4 rue des Maraîchers\n69100 Villeurbanne","siren":"882314578","vatNumber":""}'::jsonb, due_date = t - 40 + 30, finalised_at = (t - 40) + time '10:30', finalised_by = 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', sent_at = (t - 40) + time '10:30', sent_by = 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', emailed_to = null, reminders = 1, reminded_at = (t - 3) + time '10:30' where id = doc;
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('invoice', 'draft', 3, 'Maintenance du site — trimestre 3', 'fr', 'EUR', 30, 'standard', '', null, null, null, 'mbr_camilleaaaaaaaaaaaaaaaaaaa', (t - 23) + time '10:30', (t - 23) + time '10:30', null, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'line', 8, 'Maintenance
Mises à jour et petites corrections.', 3000, 'mois', 9000, 0, 2000, false, 27000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 2, 'line', 9, 'Nom de domaine', 1000, 'an', 1800, 0, 2000, false, 1800);
update documents set net = 28800, vat = 5760, gross = 34560, rates = '[{"rate":2000,"base":28800,"vat":5760}]'::jsonb, status = 'final', number = 'F-'||y||'-0004', year = to_char(current_date, 'YYYY')::int, seq = 4, issue_date = t - 22, seller = '{"legalName":"Atelier Martin SARL","tradeName":"Atelier Martin","legalForm":"SARL","capital":1000000,"address":"12 rue des Tanneurs","postcode":"69002","city":"Lyon","country":"FR","siren":"853128940","siret":"85312894000014","rcsCity":"Lyon","vatNumber":"FR25853128940","franchise":false,"vatOnDebits":false,"email":"bonjour@atelier-martin.test","phone":"04 78 42 18 90","website":"atelier-martin.test","bank":"Banque Populaire","iban":"FR76 3000 6000 0112 3456 7890 189","bic":"AGRIFRPP","logo":null,"logoType":null,"paymentDays":30,"penaltyRate":null,"earlyDiscount":"","footer":"Assurance responsabilité civile professionnelle : Hiscox, contrat n° HX-2291-778, couverture France et Union européenne."}'::jsonb, buyer = '{"kind":"company","name":"Cabinet Lefort Avocats","contact":"Hélène Lefort","email":"secretariat@lefort-avocats.test","address":"8 quai Saint-Antoine\n3e étage","postcode":"69002","city":"Lyon","country":"FR","deliveryAddress":"","siren":"904123452","vatNumber":"FR11904123452"}'::jsonb, due_date = t - 22 + 30, finalised_at = (t - 22) + time '10:30', finalised_by = 'mbr_camilleaaaaaaaaaaaaaaaaaaa', sent_at = (t - 22) + time '10:30', sent_by = 'mbr_camilleaaaaaaaaaaaaaaaaaaa', emailed_to = 'secretariat@lefort-avocats.test' where id = doc;
insert into payments (document_id, paid_on, amount, method, note, created_by, created_at) values (doc, t - 8, 15000, 'transfer', 'VIR CABINET LEFORT', 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', (t - 8) + time '10:30');
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('credit', 'draft', 3, 'Maintenance du site — trimestre 3', 'fr', 'EUR', 0, 'standard', '', null, null, 12, 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', (t - 20) + time '10:30', (t - 20) + time '10:30', null, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'line', null, 'Maintenance — septembre, non réalisée', 1000, 'mois', 9000, 0, 2000, false, 9000);
update documents set net = 9000, vat = 1800, gross = 10800, rates = '[{"rate":2000,"base":9000,"vat":1800}]'::jsonb, status = 'final', number = 'A-'||y||'-0001', year = to_char(current_date, 'YYYY')::int, seq = 1, issue_date = t - 18, seller = '{"legalName":"Atelier Martin SARL","tradeName":"Atelier Martin","legalForm":"SARL","capital":1000000,"address":"12 rue des Tanneurs","postcode":"69002","city":"Lyon","country":"FR","siren":"853128940","siret":"85312894000014","rcsCity":"Lyon","vatNumber":"FR25853128940","franchise":false,"vatOnDebits":false,"email":"bonjour@atelier-martin.test","phone":"04 78 42 18 90","website":"atelier-martin.test","bank":"Banque Populaire","iban":"FR76 3000 6000 0112 3456 7890 189","bic":"AGRIFRPP","logo":null,"logoType":null,"paymentDays":30,"penaltyRate":null,"earlyDiscount":"","footer":"Assurance responsabilité civile professionnelle : Hiscox, contrat n° HX-2291-778, couverture France et Union européenne."}'::jsonb, buyer = '{"kind":"company","name":"Cabinet Lefort Avocats","contact":"Hélène Lefort","email":"secretariat@lefort-avocats.test","address":"8 quai Saint-Antoine\n3e étage","postcode":"69002","city":"Lyon","country":"FR","deliveryAddress":"","siren":"904123452","vatNumber":"FR11904123452"}'::jsonb, finalised_at = (t - 18) + time '10:30', finalised_by = 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', sent_at = (t - 18) + time '10:30', sent_by = 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', emailed_to = 'secretariat@lefort-avocats.test' where id = doc;
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('invoice', 'draft', 4, 'Website redesign — phase 1', 'en', 'EUR', 30, 'reverse_charge', '', 5, null, null, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', (t - 15) + time '10:30', (t - 15) + time '10:30', null, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'line', null, 'Discovery workshop', 1000, 'day', 65000, 0, 2000, false, 65000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 2, 'line', null, 'Page mock-ups', 6000, 'page', 42000, 1000, 2000, false, 226800);
update documents set net = 291800, vat = 0, gross = 291800, rates = '[{"rate":0,"base":291800,"vat":0}]'::jsonb, status = 'final', number = 'F-'||y||'-0005', year = to_char(current_date, 'YYYY')::int, seq = 5, issue_date = t - 14, seller = '{"legalName":"Atelier Martin SARL","tradeName":"Atelier Martin","legalForm":"SARL","capital":1000000,"address":"12 rue des Tanneurs","postcode":"69002","city":"Lyon","country":"FR","siren":"853128940","siret":"85312894000014","rcsCity":"Lyon","vatNumber":"FR25853128940","franchise":false,"vatOnDebits":false,"email":"bonjour@atelier-martin.test","phone":"04 78 42 18 90","website":"atelier-martin.test","bank":"Banque Populaire","iban":"FR76 3000 6000 0112 3456 7890 189","bic":"AGRIFRPP","logo":null,"logoType":null,"paymentDays":30,"penaltyRate":null,"earlyDiscount":"","footer":"Assurance responsabilité civile professionnelle : Hiscox, contrat n° HX-2291-778, couverture France et Union européenne."}'::jsonb, buyer = '{"kind":"company","name":"Studio Verbeke BV","contact":"Pieter Verbeke","email":"finance@verbeke.test","address":"Rue Antoine Dansaert 92","postcode":"1000","city":"Bruxelles","country":"BE","deliveryAddress":"","siren":"","vatNumber":"BE0765432146"}'::jsonb, due_date = t - 14 + 30, finalised_at = (t - 14) + time '10:30', finalised_by = 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', sent_at = (t - 14) + time '10:30', sent_by = 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', emailed_to = 'finance@verbeke.test' where id = doc;
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('invoice', 'draft', 1, 'Refonte du site vitrine — solde', 'fr', 'EUR', 30, 'standard', '', 1, null, null, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', (t - 6) + time '10:30', (t - 6) + time '10:30', null, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'section', null, 'Conception', 0, '', 0, 0, 0, false, 0);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 2, 'line', 2, 'Atelier de cadrage
Une demi-journée avec vos équipes : objectifs, publics, contenus.', 1000, 'forfait', 38000, 0, 2000, false, 38000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 3, 'line', 3, 'Maquette de page
Une page, deux allers-retours inclus.', 4000, 'page', 42000, 0, 2000, false, 168000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 4, 'section', null, 'Réalisation', 0, '', 0, 0, 0, false, 0);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 5, 'line', 4, 'Développement web
Intégration et développement du site.', 5000, 'jour', 60000, 0, 2000, false, 300000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 6, 'line', 7, 'Hébergement annuel
Serveur en France, sauvegardes quotidiennes.', 1000, 'an', 24000, 0, 2000, false, 24000);
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 7, 'line', null, replace('Déduction de la facture d’acompte F-{Y}-0001', '{Y}', y), 1000, '', -159000, 0, 2000, false, -159000);
update documents set net = 371000, vat = 74200, gross = 445200, rates = '[{"rate":2000,"base":371000,"vat":74200}]'::jsonb, status = 'final', number = 'F-'||y||'-0006', year = to_char(current_date, 'YYYY')::int, seq = 6, issue_date = t - 5, seller = '{"legalName":"Atelier Martin SARL","tradeName":"Atelier Martin","legalForm":"SARL","capital":1000000,"address":"12 rue des Tanneurs","postcode":"69002","city":"Lyon","country":"FR","siren":"853128940","siret":"85312894000014","rcsCity":"Lyon","vatNumber":"FR25853128940","franchise":false,"vatOnDebits":false,"email":"bonjour@atelier-martin.test","phone":"04 78 42 18 90","website":"atelier-martin.test","bank":"Banque Populaire","iban":"FR76 3000 6000 0112 3456 7890 189","bic":"AGRIFRPP","logo":null,"logoType":null,"paymentDays":30,"penaltyRate":null,"earlyDiscount":"","footer":"Assurance responsabilité civile professionnelle : Hiscox, contrat n° HX-2291-778, couverture France et Union européenne."}'::jsonb, buyer = '{"kind":"company","name":"Boulangerie Dupain SAS","contact":"Marie Dupain","email":"marie@dupain.test","address":"3 place Bellecour","postcode":"69002","city":"Lyon","country":"FR","deliveryAddress":"","siren":"812345676","vatNumber":"FR19812345676"}'::jsonb, due_date = t - 5 + 30, finalised_at = (t - 5) + time '10:30', finalised_by = 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa' where id = doc;
insert into documents (type, status, client_id, title, language, currency, payment_days, vat_treatment, notes, quote_id, deposit_percent, invoice_id, created_by, created_at, updated_at, valid_until, delivery_date)
  values ('invoice', 'draft', 6, 'Faire-part de mariage — acompte', 'fr', 'EUR', 30, 'standard', '', null, null, null, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', (t - 1) + time '10:30', (t - 1) + time '10:30', null, null) returning id into doc;
insert into lines (document_id, position, kind, item_id, description, quantity, unit, unit_price, discount, vat_rate, goods, net) values (doc, 1, 'line', null, 'Acompte sur la création des faire-part', 1000, '', 20000, 0, 2000, false, 20000);
update documents set net = 20000, vat = 4000, gross = 24000, rates = '[{"rate":2000,"base":20000,"vat":4000}]'::jsonb, ready_at = now() - interval '2 hours' where id = doc;
insert into counters (type, year, last) values ('quote', to_char(current_date, 'YYYY')::int, 6), ('invoice', to_char(current_date, 'YYYY')::int, 6), ('credit', to_char(current_date, 'YYYY')::int, 1);
-- The client's answer link of quote D-…-0006 (its page, /q/<secret>): a
-- fixed secret, so the screenshots and the flows can open it.
insert into quote_links (document_id, secret, secret_hash, created_by, created_at)
  select id, 'SampleAnswerLinkQuoteD0006Roux01', encode(sha256(convert_to('SampleAnswerLinkQuoteD0006Roux01', 'UTF8')), 'hex'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', sent_at
  from documents where type = 'quote' and seq = 6;
end $$;
