-- Sample data for local runs and screenshots (never run by the Chest): the
-- client book of Atelier Martin, a small French company that furnishes and
-- fits out offices. Member ids are those of the studio's dev harness
-- (lab/chest-dev/cast.mjs): Camille (manager), Inès, Hugo and Sofia (sales).
-- Dates are relative to today in Paris (the Chest's time zone), so the
-- screens always look current.

insert into companies (name, website, phone, address, industry, tags, owner, notes, created_by, created_at) values
  ('Boulangeries Durand', 'durand-boulangeries.fr', '04 78 42 16 90', E'12 rue de la République\n69002 Lyon', 'Food retail', '{"retail","key account"}', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 'Twelve shops around Lyon. Head office moving in spring.', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '120 days'),
  ('Cabinet Lefèvre Avocats', 'lefevre-avocats.fr', '01 44 55 21 70', E'48 boulevard Haussmann\n75009 Paris', 'Law firm', '{"services"}', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', '', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '111 days'),
  ('Garage Petit & Fils', 'garage-petit.fr', '02 40 12 88 31', E'7 route de Vannes\n44100 Nantes', 'Car repair', '{}', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', '', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '102 days'),
  ('Imprimerie Roux', 'imprimerie-roux.fr', '05 56 31 44 02', E'3 quai de Bacalan\n33300 Bordeaux', 'Printing', '{}', 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', 'Family business, prefers email.', 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', now() - interval '93 days'),
  ('Clinique Vétérinaire des Tilleuls', 'vet-tilleuls.fr', '03 88 22 10 45', E'21 allée des Tilleuls\n67000 Strasbourg', 'Veterinary', '{"health"}', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', '', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '84 days'),
  ('Nouvelle Boulangerie', 'nouvelle-boulangerie.fr', '04 72 10 33 58', E'5 place Bellecour\n69002 Lyon', 'Food retail', '{"retail"}', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', '', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '75 days'),
  ('Studio Blanc Architecture', 'studio-blanc.fr', '01 42 71 09 16', E'19 rue Charlot\n75003 Paris', 'Architecture', '{"partner"}', 'mbr_camilleaaaaaaaaaaaaaaaaaaa', 'Sends us fit-out projects.', 'mbr_camilleaaaaaaaaaaaaaaaaaaa', now() - interval '66 days'),
  ('Hôtel Le Méridien Sud', 'hotel-meridien-sud.fr', '04 91 54 20 00', E'60 La Canebière\n13001 Marseille', 'Hospitality', '{"key account"}', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', '', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '57 days'),
  ('Coopérative Agricole du Val', 'coop-du-val.fr', '02 47 58 61 12', E'Zone artisanale des Granges\n37400 Amboise', 'Agriculture', '{}', 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', '', 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', now() - interval '48 days'),
  ('Mairie de Saint-Aubin', 'saint-aubin.fr', '02 99 45 11 20', E'Place de la Mairie\n35250 Saint-Aubin', 'Public sector', '{"public tender"}', 'mbr_camilleaaaaaaaaaaaaaaaaaaa', 'Public tender rules apply: quotes through their platform.', 'mbr_camilleaaaaaaaaaaaaaaaaaaa', now() - interval '39 days');

insert into contacts (name, email, phone, title, company_id, owner, last_contact_at, tags, created_by, created_at) values
  ('Claire Durand', 'claire.durand@durand-boulangeries.fr', '06 12 34 56 78', 'Purchasing manager', (select id from companies where name = 'Boulangeries Durand'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '2 days', '{"decision maker"}', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '110 days'),
  ('Marc Durand', 'marc.durand@durand-boulangeries.fr', '06 22 41 90 13', 'Managing director', (select id from companies where name = 'Boulangeries Durand'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '20 days', '{}', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '105 days'),
  ('Élodie Lefèvre', 'e.lefevre@lefevre-avocats.fr', '01 44 55 21 72', 'Partner', (select id from companies where name = 'Cabinet Lefèvre Avocats'), 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '5 days', '{"decision maker"}', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '100 days'),
  ('Julien Moreau', 'j.moreau@lefevre-avocats.fr', '01 44 55 21 75', 'Office manager', (select id from companies where name = 'Cabinet Lefèvre Avocats'), 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '9 days', '{}', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '95 days'),
  ('Pierre Petit', 'pierre@garage-petit.fr', '06 71 08 33 20', 'Owner', (select id from companies where name = 'Garage Petit & Fils'), 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '1 days', '{}', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '90 days'),
  ('Hélène Roux', 'helene@imprimerie-roux.fr', '05 56 31 44 00', 'Director', (select id from companies where name = 'Imprimerie Roux'), 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', now() - interval '12 days', '{}', 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', now() - interval '85 days'),
  ('Dr Nadia Chérif', 'n.cherif@vet-tilleuls.fr', '03 88 22 10 40', 'Head vet', (select id from companies where name = 'Clinique Vétérinaire des Tilleuls'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '3 days', '{}', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '80 days'),
  ('Thomas Girard', 'thomas.girard@vet-tilleuls.fr', '', 'Practice manager', (select id from companies where name = 'Clinique Vétérinaire des Tilleuls'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', null, '{}', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '75 days'),
  ('Lucie Martin', 'lucie@nouvelle-boulangerie.fr', '06 55 10 22 87', 'Founder', (select id from companies where name = 'Nouvelle Boulangerie'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '40 days', '{}', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '70 days'),
  ('Sophie Blanc', 'sophie@studio-blanc.fr', '06 44 91 20 36', 'Architect, founder', (select id from companies where name = 'Studio Blanc Architecture'), 'mbr_camilleaaaaaaaaaaaaaaaaaaa', now() - interval '7 days', '{"partner"}', 'mbr_camilleaaaaaaaaaaaaaaaaaaa', now() - interval '65 days'),
  ('Antoine Vidal', 'a.vidal@hotel-meridien-sud.fr', '04 91 54 20 12', 'General manager', (select id from companies where name = 'Hôtel Le Méridien Sud'), 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '15 days', '{"decision maker"}', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '60 days'),
  ('Camille Rey', 'c.rey@hotel-meridien-sud.fr', '04 91 54 20 15', 'Operations', (select id from companies where name = 'Hôtel Le Méridien Sud'), 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '4 days', '{}', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '55 days'),
  ('Bernard Fabre', 'b.fabre@coop-du-val.fr', '02 47 58 61 10', 'Chairman', (select id from companies where name = 'Coopérative Agricole du Val'), 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', now() - interval '60 days', '{}', 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', now() - interval '50 days'),
  ('Isabelle Noël', 'dgs@saint-aubin.fr', '02 99 45 11 22', 'Director general of services', (select id from companies where name = 'Mairie de Saint-Aubin'), 'mbr_camilleaaaaaaaaaaaaaaaaaaa', now() - interval '25 days', '{}', 'mbr_camilleaaaaaaaaaaaaaaaaaaa', now() - interval '45 days'),
  ('Paul Garnier', 'paul.garnier@gmail.com', '06 98 12 45 70', 'Freelance facility consultant', null, 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', now() - interval '1300 days', '{"prospect"}', 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', now() - interval '1400 days');

insert into deals (title, company_id, contact_id, value_cents, stage_id, position, expected_close, owner, reason, closed_at, created_by, created_at) values
  ('Head office fit-out, 40 desks', (select id from companies where name = 'Boulangeries Durand'), (select id from contacts where name = 'Claire Durand'), 4850000, (select id from stages where key = 'proposal'), 'm', (now() at time zone 'Europe/Paris')::date + 24, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', '', null, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '80 days'),
  ('Shop counters, 3 new bakeries', (select id from companies where name = 'Boulangeries Durand'), (select id from contacts where name = 'Marc Durand'), 1860000, (select id from stages where key = 'qualified'), 'm', (now() at time zone 'Europe/Paris')::date + 55, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', '', null, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '75 days'),
  ('Meeting room furniture', (select id from companies where name = 'Cabinet Lefèvre Avocats'), (select id from contacts where name = 'Élodie Lefèvre'), 920000, (select id from stages where key = 'negotiation'), 'm', (now() at time zone 'Europe/Paris')::date + 9, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', '', null, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '70 days'),
  ('Workshop office and lockers', (select id from companies where name = 'Garage Petit & Fils'), (select id from contacts where name = 'Pierre Petit'), 640000, (select id from stages where key = 'lead'), 'm', (now() at time zone 'Europe/Paris')::date + 70, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', '', null, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '65 days'),
  ('Open space acoustic panels', (select id from companies where name = 'Imprimerie Roux'), (select id from contacts where name = 'Hélène Roux'), 380000, (select id from stages where key = 'lead'), 't', null, 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', '', null, 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', now() - interval '60 days'),
  ('Waiting room refit', (select id from companies where name = 'Clinique Vétérinaire des Tilleuls'), (select id from contacts where name = 'Dr Nadia Chérif'), 1250000, (select id from stages where key = 'proposal'), 't', (now() at time zone 'Europe/Paris')::date + 18, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', '', null, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '55 days'),
  ('Café seating, 60 chairs', (select id from companies where name = 'Nouvelle Boulangerie'), (select id from contacts where name = 'Lucie Martin'), 1120000, (select id from stages where key = 'lost'), 'm', null, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 'Went with a competitor', now() - interval '12 days', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '50 days'),
  ('Studio desks, second floor', (select id from companies where name = 'Studio Blanc Architecture'), (select id from contacts where name = 'Sophie Blanc'), 2780000, (select id from stages where key = 'negotiation'), 't', (now() at time zone 'Europe/Paris')::date + 14, 'mbr_camilleaaaaaaaaaaaaaaaaaaa', '', null, 'mbr_camilleaaaaaaaaaaaaaaaaaaa', now() - interval '45 days'),
  ('Lobby and 12 suites', (select id from companies where name = 'Hôtel Le Méridien Sud'), (select id from contacts where name = 'Antoine Vidal'), 9600000, (select id from stages where key = 'qualified'), 't', (now() at time zone 'Europe/Paris')::date + 85, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', '', null, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '40 days'),
  ('Staff room', (select id from companies where name = 'Hôtel Le Méridien Sud'), (select id from contacts where name = 'Camille Rey'), 450000, (select id from stages where key = 'won'), 'm', null, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', 'Fast delivery before the season', now() - interval '6 days', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '35 days'),
  ('Offices for the new cooperative shop', (select id from companies where name = 'Coopérative Agricole du Val'), (select id from contacts where name = 'Bernard Fabre'), 1540000, (select id from stages where key = 'lead'), 'z', (now() at time zone 'Europe/Paris')::date + 120, 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', '', null, 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', now() - interval '30 days'),
  ('Town hall reception desk', (select id from companies where name = 'Mairie de Saint-Aubin'), (select id from contacts where name = 'Isabelle Noël'), 2300000, (select id from stages where key = 'proposal'), 'z', (now() at time zone 'Europe/Paris')::date + 40, 'mbr_camilleaaaaaaaaaaaaaaaaaaa', '', null, 'mbr_camilleaaaaaaaaaaaaaaaaaaa', now() - interval '25 days');

insert into steps (deal_id, contact_id, text, due_on, owner, created_by) values
  ((select id from deals where title = 'Head office fit-out, 40 desks'), null, 'Send the revised quote with the 3D plan', (now() at time zone 'Europe/Paris')::date + 0, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa'),
  ((select id from deals where title = 'Waiting room refit'), null, 'Call Dr Chérif about fabric samples', (now() at time zone 'Europe/Paris')::date + -1, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa'),
  ((select id from deals where title = 'Shop counters, 3 new bakeries'), null, 'Visit the Croix-Rousse shop to measure', (now() at time zone 'Europe/Paris')::date + 2, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa'),
  (null, (select id from contacts where name = 'Lucie Martin'), 'Ask how the new café is going', (now() at time zone 'Europe/Paris')::date + 5, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa'),
  ((select id from deals where title = 'Meeting room furniture'), null, 'Confirm delivery date with Julien', (now() at time zone 'Europe/Paris')::date + 0, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa'),
  ((select id from deals where title = 'Lobby and 12 suites'), null, 'Prepare the moodboard for the visit', (now() at time zone 'Europe/Paris')::date + 3, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa'),
  ((select id from deals where title = 'Workshop office and lockers'), null, 'First call: understand the need', (now() at time zone 'Europe/Paris')::date + -2, 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa'),
  ((select id from deals where title = 'Studio desks, second floor'), null, 'Negotiate the final discount', (now() at time zone 'Europe/Paris')::date + 1, 'mbr_camilleaaaaaaaaaaaaaaaaaaa', 'mbr_camilleaaaaaaaaaaaaaaaaaaa'),
  ((select id from deals where title = 'Town hall reception desk'), null, 'Answer the tender questions', (now() at time zone 'Europe/Paris')::date + 6, 'mbr_camilleaaaaaaaaaaaaaaaaaaa', 'mbr_camilleaaaaaaaaaaaaaaaaaaa'),
  ((select id from deals where title = 'Open space acoustic panels'), null, 'Book a showroom visit', (now() at time zone 'Europe/Paris')::date + 4, 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa'),
  (null, (select id from contacts where name = 'Thomas Girard'), 'Introduce ourselves by email', (now() at time zone 'Europe/Paris')::date + 0, 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa');

insert into activities (kind, body, data, deal_id, company_id, contact_id, author, at, created_at) values
  ('created', '', '{}', (select id from deals where title = 'Head office fit-out, 40 desks'), (select company_id from deals where title = 'Head office fit-out, 40 desks'), (select contact_id from deals where title = 'Head office fit-out, 40 desks'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '960 hours', now() - interval '960 hours'),
  ('meeting', 'Visited the new head office with Claire. 40 desks, 2 meeting rooms, a break area. Budget around €50k, decision before the end of the month.', '{}', (select id from deals where title = 'Head office fit-out, 40 desks'), (select company_id from deals where title = 'Head office fit-out, 40 desks'), (select contact_id from deals where title = 'Head office fit-out, 40 desks'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '504 hours', now() - interval '504 hours'),
  ('stage', '', '{"from": "__lead", "to": "__proposal"}', (select id from deals where title = 'Head office fit-out, 40 desks'), (select company_id from deals where title = 'Head office fit-out, 40 desks'), (select contact_id from deals where title = 'Head office fit-out, 40 desks'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '480 hours', now() - interval '480 hours'),
  ('call', 'Claire wants height-adjustable desks for half of the team. Revised quote needed.', '{}', (select id from deals where title = 'Head office fit-out, 40 desks'), (select company_id from deals where title = 'Head office fit-out, 40 desks'), (select contact_id from deals where title = 'Head office fit-out, 40 desks'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '51 hours', now() - interval '51 hours'),
  ('email', 'Sent the first quote and the catalogue.', '{}', (select id from deals where title = 'Head office fit-out, 40 desks'), (select company_id from deals where title = 'Head office fit-out, 40 desks'), (select contact_id from deals where title = 'Head office fit-out, 40 desks'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '456 hours', now() - interval '456 hours'),
  ('call', 'Dr Chérif likes the proposal; she wants to see fabric samples before choosing.', '{}', (select id from deals where title = 'Waiting room refit'), (select company_id from deals where title = 'Waiting room refit'), (select contact_id from deals where title = 'Waiting room refit'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '72 hours', now() - interval '72 hours'),
  ('note', 'Clinic open Saturday mornings: deliver on a Sunday or in the evening.', '{}', (select id from deals where title = 'Waiting room refit'), (select company_id from deals where title = 'Waiting room refit'), (select contact_id from deals where title = 'Waiting room refit'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '144 hours', now() - interval '144 hours'),
  ('meeting', 'Showroom visit with Élodie and Julien. They chose the oak table, 12 seats.', '{}', (select id from deals where title = 'Meeting room furniture'), (select company_id from deals where title = 'Meeting room furniture'), (select contact_id from deals where title = 'Meeting room furniture'), 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '120 hours', now() - interval '120 hours'),
  ('call', 'Julien asks for a 5% discount if we deliver in two weeks.', '{}', (select id from deals where title = 'Meeting room furniture'), (select company_id from deals where title = 'Meeting room furniture'), (select contact_id from deals where title = 'Meeting room furniture'), 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '26 hours', now() - interval '26 hours'),
  ('call', 'Pierre called after seeing our van. Small project, but his brother owns two garages.', '{}', (select id from deals where title = 'Workshop office and lockers'), (select company_id from deals where title = 'Workshop office and lockers'), (select contact_id from deals where title = 'Workshop office and lockers'), 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '624 hours', now() - interval '624 hours'),
  ('meeting', 'First meeting with Antoine Vidal. Full refurbishment of the lobby before next summer; 12 suites later.', '{}', (select id from deals where title = 'Lobby and 12 suites'), (select company_id from deals where title = 'Lobby and 12 suites'), (select contact_id from deals where title = 'Lobby and 12 suites'), 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '360 hours', now() - interval '360 hours'),
  ('email', 'Sent references: two hotels in Nice and Cannes.', '{}', (select id from deals where title = 'Lobby and 12 suites'), (select company_id from deals where title = 'Lobby and 12 suites'), (select contact_id from deals where title = 'Lobby and 12 suites'), 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '336 hours', now() - interval '336 hours'),
  ('won', 'Fast delivery before the season', '{"value": 0}', (select id from deals where title = 'Staff room'), (select company_id from deals where title = 'Staff room'), (select contact_id from deals where title = 'Staff room'), 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '144 hours', now() - interval '144 hours'),
  ('lost', 'Went with a competitor', '{"value": 0}', (select id from deals where title = 'Café seating, 60 chairs'), (select company_id from deals where title = 'Café seating, 60 chairs'), (select contact_id from deals where title = 'Café seating, 60 chairs'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '288 hours', now() - interval '288 hours'),
  ('call', 'Sophie agrees on the design; she asks for a final discount on the whole order.', '{}', (select id from deals where title = 'Studio desks, second floor'), (select company_id from deals where title = 'Studio desks, second floor'), (select contact_id from deals where title = 'Studio desks, second floor'), 'mbr_camilleaaaaaaaaaaaaaaaaaaa', now() - interval '168 hours', now() - interval '168 hours'),
  ('meeting', 'Site visit with the director general of services. The tender closes in six weeks.', '{}', (select id from deals where title = 'Town hall reception desk'), (select company_id from deals where title = 'Town hall reception desk'), (select contact_id from deals where title = 'Town hall reception desk'), 'mbr_camilleaaaaaaaaaaaaaaaaaaa', now() - interval '600 hours', now() - interval '600 hours'),
  ('note', 'Board meeting next quarter decides the budget.', '{}', (select id from deals where title = 'Offices for the new cooperative shop'), (select company_id from deals where title = 'Offices for the new cooperative shop'), (select contact_id from deals where title = 'Offices for the new cooperative shop'), 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', now() - interval '1440 hours', now() - interval '1440 hours');

-- The stage change above names the stages by id.
update activities set data = jsonb_build_object('from', (select id from stages where key = 'lead'), 'to', (select id from stages where key = 'proposal')) where kind = 'stage';

insert into activities (kind, body, contact_id, company_id, author, at, created_at) values
  ('call', 'She chose another supplier for the café, but may need office furniture next year.', (select id from contacts where name = 'Lucie Martin'), (select company_id from contacts where name = 'Lucie Martin'), 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '960 hours', now() - interval '960 hours'),
  ('note', 'Met at a trade fair years ago. No news since.', (select id from contacts where name = 'Paul Garnier'), (select company_id from contacts where name = 'Paul Garnier'), 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', now() - interval '31200 hours', now() - interval '31200 hours'),
  ('call', 'Bernard confirms interest; waiting for the board.', (select id from contacts where name = 'Bernard Fabre'), (select company_id from contacts where name = 'Bernard Fabre'), 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', now() - interval '1440 hours', now() - interval '1440 hours'),
  ('meeting', 'Lunch with Sophie: two new fit-out projects expected in Paris this autumn.', (select id from contacts where name = 'Sophie Blanc'), (select company_id from contacts where name = 'Sophie Blanc'), 'mbr_camilleaaaaaaaaaaaaaaaaaaa', now() - interval '480 hours', now() - interval '480 hours');

insert into activities (kind, body, company_id, author, at, created_at) values
  ('note', 'Their purchasing goes through a yearly framework agreement: renew in January.', (select id from companies where name = 'Boulangeries Durand'), 'mbr_camilleaaaaaaaaaaaaaaaaaaa', now() - interval '30 days', now() - interval '30 days');
-- Everything else was added by its owner.
insert into activities (kind, company_id, author, at, created_at)
  select 'created', id, created_by, created_at, created_at from companies;
insert into activities (kind, contact_id, company_id, author, at, created_at)
  select 'created', id, company_id, created_by, created_at, created_at from contacts;
insert into activities (kind, deal_id, company_id, contact_id, author, at, created_at)
  select 'created', d.id, d.company_id, d.contact_id, d.created_by, d.created_at, d.created_at from deals d where d.title <> 'Head office fit-out, 40 desks';

-- Second version: addresses in parts, legal identities (fictional numbers of
-- a valid shape), the team's own fields, several next steps with a time, a
-- step of one's own, and deals closed in the past months (the Team page).
update companies set address = split_part(address, E'\n', 1), postcode = split_part(split_part(address, E'\n', 2), ' ', 1),
  city = substr(split_part(address, E'\n', 2), length(split_part(split_part(address, E'\n', 2), ' ', 1)) + 2), country = 'FR';
update companies set siren = '362275869', vat = 'FR43362275869', email = 'compta@durand-boulangeries.fr' where name = 'Boulangeries Durand';
update companies set siren = '530530419', vat = 'FR40530530419' where name = 'Cabinet Lefèvre Avocats';
update companies set siren = '749008934', vat = 'FR86749008934' where name = 'Hôtel Le Méridien Sud';
update companies set siren = '353246119' where name = 'Studio Blanc Architecture';

insert into fields (object, label, kind, options, position) values
  ('companies', 'Segment', 'choice', '{"Small business","Mid-market","Key account"}', 0),
  ('companies', 'Employees', 'number', '{}', 1),
  ('contacts', 'Lead source', 'choice', '{"Referral","Trade fair","Website","Cold call"}', 0),
  ('deals', 'Competitor', 'text', '{}', 0),
  ('deals', 'Delivery wanted by', 'date', '{}', 1);
update companies set custom = jsonb_build_object((select id::text from fields where label = 'Segment'), 'Key account', (select id::text from fields where label = 'Employees'), 140) where name in ('Boulangeries Durand', 'Hôtel Le Méridien Sud');
update companies set custom = jsonb_build_object((select id::text from fields where label = 'Segment'), 'Small business', (select id::text from fields where label = 'Employees'), 12) where name in ('Garage Petit & Fils', 'Imprimerie Roux', 'Nouvelle Boulangerie');
update companies set custom = jsonb_build_object((select id::text from fields where label = 'Segment'), 'Mid-market', (select id::text from fields where label = 'Employees'), 35) where name in ('Cabinet Lefèvre Avocats', 'Clinique Vétérinaire des Tilleuls', 'Studio Blanc Architecture');
update contacts set custom = jsonb_build_object((select id::text from fields where label = 'Lead source'), 'Trade fair') where name in ('Claire Durand', 'Pierre Petit', 'Bernard Fabre');
update contacts set custom = jsonb_build_object((select id::text from fields where label = 'Lead source'), 'Referral') where name in ('Élodie Lefèvre', 'Dr Nadia Chérif', 'Antoine Vidal');
update contacts set phone2 = '04 78 42 16 91', url = 'linkedin.com/in/claire-durand-achats' where name = 'Claire Durand';
update deals set custom = jsonb_build_object((select id::text from fields where label = 'Competitor'), 'Bureau Direct', (select id::text from fields where label = 'Delivery wanted by'), to_char((now() at time zone 'Europe/Paris')::date + 60, 'YYYY-MM-DD')) where title = 'Head office fit-out, 40 desks';
update deals set custom = jsonb_build_object((select id::text from fields where label = 'Competitor'), 'Mobilier Pro') where title in ('Meeting room furniture', 'Studio desks, second floor');

update steps set due_time = '10:00' where text = 'Send the revised quote with the 3D plan';
update steps set due_time = '14:30' where text = 'Confirm delivery date with Julien';
insert into steps (deal_id, contact_id, text, due_on, due_time, owner, created_by) values
  ((select id from deals where title = 'Head office fit-out, 40 desks'), null, 'Call Claire to walk through the plan', (now() at time zone 'Europe/Paris')::date + 2, '11:00', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa'),
  (null, null, 'Prepare the stand for the Lyon trade fair', (now() at time zone 'Europe/Paris')::date + 3, null, 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa');

insert into deals (title, company_id, contact_id, value_cents, stage_id, position, owner, reason, closed_at, created_by, created_at) values
  ('Reception area, second shop', (select id from companies where name = 'Boulangeries Durand'), (select id from contacts where name = 'Claire Durand'), 1480000, (select id from stages where key = 'won'), 'n', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 'Best layout', now() - interval '40 days', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '100 days'),
  ('Archive shelving', (select id from companies where name = 'Cabinet Lefèvre Avocats'), (select id from contacts where name = 'Julien Moreau'), 610000, (select id from stages where key = 'won'), 'n', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', 'Price', now() - interval '70 days', 'mbr_hugoaaaaaaaaaaaaaaaaaaaaaa', now() - interval '110 days'),
  ('Print shop break room', (select id from companies where name = 'Imprimerie Roux'), (select id from contacts where name = 'Hélène Roux'), 290000, (select id from stages where key = 'lost'), 'n', 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', 'No budget', now() - interval '55 days', 'mbr_sofiaaaaaaaaaaaaaaaaaaaaaa', now() - interval '90 days'),
  ('Partner showroom', (select id from companies where name = 'Studio Blanc Architecture'), (select id from contacts where name = 'Sophie Blanc'), 3350000, (select id from stages where key = 'won'), 'n', 'mbr_camilleaaaaaaaaaaaaaaaaaaa', 'Long-standing partner', now() - interval '100 days', 'mbr_camilleaaaaaaaaaaaaaaaaaaa', now() - interval '130 days'),
  ('Clinic reception desk', (select id from companies where name = 'Clinique Vétérinaire des Tilleuls'), (select id from contacts where name = 'Dr Nadia Chérif'), 540000, (select id from stages where key = 'lost'), 'n', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', 'Went with a competitor', now() - interval '85 days', 'mbr_inesaaaaaaaaaaaaaaaaaaaaaa', now() - interval '120 days');
insert into activities (kind, deal_id, company_id, contact_id, author, at, created_at)
  select 'created', d.id, d.company_id, d.contact_id, d.created_by, d.created_at, d.created_at from deals d where d.position = 'n';
