// Self-hosts a font in a tool: the tool has no network, so its fonts are its
// own files. Takes a Fontsource package from npm (open-licence fonts, mostly
// OFL-1.1), copies its latin and latin-ext WOFF2 files into
// <tool>/public/fonts/, writes the @font-face rules into
// <tool>/app/fonts/<family>.css and the font's licence next to the files.
//
//   node scripts/add-font.mjs <tool folder> <package> [weights] [--italic]
//   node scripts/add-font.mjs tools/private/tasks @fontsource-variable/figtree
//   node scripts/add-font.mjs tools/private/wiki @fontsource/literata 400,600 --italic
//
// A variable package (@fontsource-variable/…) gives one file per subset and
// style; a static one (@fontsource/…) one per weight: name the weights
// (400 by default).
import { execFileSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const [folder, pkg, weightsArg, ...flags] = process.argv.slice(2);
if (!folder || !pkg || !existsSync(join(folder, "package.json"))) {
  console.error("usage: node scripts/add-font.mjs <tool folder> <@fontsource… package> [weights] [--italic]");
  process.exit(1);
}
const italic = flags.includes("--italic") || weightsArg === "--italic";
const weights = weightsArg && weightsArg !== "--italic" ? weightsArg.split(",") : ["400"];
const tool = resolve(folder);
const work = mkdtempSync(join(tmpdir(), "font-"));
try {
  execFileSync("npm", ["pack", pkg, "--pack-destination", work], { stdio: ["ignore", "ignore", "inherit"] });
  const tarball = readdirSync(work).find(f => f.endsWith(".tgz"));
  execFileSync("tar", ["xzf", join(work, tarball), "-C", work]);
  const dir = join(work, "package");
  const meta = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  const variable = pkg.startsWith("@fontsource-variable/");
  const slug = pkg.split("/")[1];
  // Every @font-face of the package, for all the weights and styles asked.
  const cssFiles = [join(dir, "index.css")];
  if (variable && italic && existsSync(join(dir, "wght-italic.css"))) cssFiles.push(join(dir, "wght-italic.css"));
  if (!variable) for (const w of weights) for (const style of italic ? ["", "-italic"] : [""]) {
    const f = join(dir, `${w}${style}.css`);
    if (existsSync(f)) cssFiles.push(f);
    else console.warn(`no weight ${w}${style} in ${pkg}`);
  }
  const faces = cssFiles.flatMap(f => readFileSync(f, "utf8").split(/(?=\/\* )/u)).filter(block => /@font-face/u.test(block) && /-(latin|latin-ext)-/u.test(block));
  const unique = [...new Set(faces)];
  const out = join(tool, "public", "fonts");
  mkdirSync(out, { recursive: true });
  const rules = [];
  for (const block of unique) {
    const file = /url\(\.\/files\/([^)]+\.woff2)\)/u.exec(block)?.[1];
    if (!file) continue;
    copyFileSync(join(dir, "files", file), join(out, file));
    rules.push(block.replace(/url\(\.\/files\/([^)]+\.woff2)\)/u, "url(/fonts/$1)").replace(/src: url\(([^)]+)\) format\('woff2-variations'\)/u, "src: url($1) format('woff2')").trim());
  }
  const family = /font-family: '([^']+)'/u.exec(unique[0] ?? "")?.[1] ?? slug;
  const licence = readdirSync(dir).find(f => /^LICEN[CS]E/u.test(f));
  if (licence) copyFileSync(join(dir, licence), join(out, `LICENSE-${slug}.txt`));
  mkdirSync(join(tool, "app", "fonts"), { recursive: true });
  writeFileSync(join(tool, "app", "fonts", `${slug}.css`), `/* ${family}: ${meta.license} — ${pkg}@${meta.version} (Fontsource), files in public/fonts/, licence in public/fonts/LICENSE-${slug}.txt. Generated by scripts/add-font.mjs. */\n\n${rules.join("\n\n")}\n`);
  console.log(`${family} (${meta.license}) → ${rules.length} faces in ${folder}/public/fonts; import "./fonts/${slug}.css" in app/layout.tsx; font-family: '${family}'`);
} finally {
  rmSync(work, { recursive: true, force: true });
}
