// The starter's and the package's sizes, as the report quotes them (run it
// before quoting: four reviews in a row found the report's figures stale).
//   node lab/starter-bench/sizes.mjs            the figures
//   node lab/starter-bench/sizes.mjs --check    the report's §5 against them
//                                               (exit 1 on a mismatch; app's npm test runs it)
//   node lab/starter-bench/sizes.mjs --write    the report's §5 figures set to the files'
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const tracked = dir => execFileSync("git", ["ls-files", dir], { cwd: root }).toString().split("\n").filter(f => f && !/(package-lock\.json|\.tgz|\.png)$/u.test(f));
const lines = files => files.reduce((n, f) => n + readFileSync(join(root, f), "utf8").split("\n").length - 1, 0);
const template = tracked("starter");
// Tests as written (each top-level test(…) call), per file.
const tests = files => files.reduce((n, f) => n + (readFileSync(join(root, f), "utf8").match(/^test\(/gmu) ?? []).length, 0);
const appVersion = JSON.parse(readFileSync(join(root, "app/package.json"), "utf8")).version;
const figures = {
  "starter: files (no lock, no tgz)": template.length,
  "starter: lines": lines(template),
  "starter/AGENTS.md: lines": lines(["starter/AGENTS.md"]),
  "app/src: lines": lines(tracked("app/src")),
  "app/test: lines": lines(tracked("app/test")),
  "app/AGENTS.md: lines": lines(["app/AGENTS.md"]),
  "reference/perseus-starter: files": tracked("reference/perseus-starter").length,
  "reference/perseus-starter: lines": lines(tracked("reference/perseus-starter")),
  "app: tests": tests(["app/test/units.test.ts", "app/test/server.test.mjs", "app/test/changes.test.mjs"]),
  "app: unit tests": tests(["app/test/units.test.ts"]),
  "app: server tests": tests(["app/test/server.test.mjs"]),
  "app: change-log tests": tests(["app/test/changes.test.mjs"]),
  "Chromium tests": tests(["lab/starter-bench/browser.test.mjs"]),
  "starter: tests": tests(tracked("starter/test").filter(f => /\.test\./u.test(f))),
};
if (!process.argv.includes("--check") && !process.argv.includes("--write")) {
  console.log(`${"app: version".padEnd(40)} ${appVersion}`);
  for (const [name, value] of Object.entries(figures)) console.log(`${name.padEnd(40)} ${value}`);
  process.exit(0);
}

// --check: the figures as reports/06-perseus-starter.md writes them, in
// the paragraph "Generated by `node lab/starter-bench/sizes.mjs`".
const report = readFileSync(join(root, "reports/06-perseus-starter.md"), "utf8");
const start = report.indexOf("Generated by `node lab/starter-bench/sizes.mjs`");
if (start < 0) {
  console.error("sizes --check: the report has no paragraph \"Generated by `node lab/starter-bench/sizes.mjs`\"");
  process.exit(1);
}
const block = report.slice(start, report.indexOf("\n\n**", start)).replace(/\s+/gu, " ");
const number = text => Number(text.replace(/,/gu, ""));
const said = {
  "starter/AGENTS.md: lines": /project's `AGENTS\.md` is ([\d,]+) lines/u,
  "app/AGENTS.md: lines": /package's `AGENTS\.md`, ([\d,]+) lines/u,
  "starter: files (no lock, no tgz)": /template is ([\d,]+) files/u,
  "starter: lines": /template is [\d,]+ files and ([\d,]+) lines/u,
  "app/src: lines": /package is ([\d,]+) lines of source/u,
  "app/test: lines": /source and ([\d,]+) of tests/u,
  "reference/perseus-starter: files": /reference starter: ([\d,]+) files/u,
  "reference/perseus-starter: lines": /reference starter: [\d,]+ files, ([\d,]+) lines/u,
  "app: tests": /package's tests: ([\d,]+) \(/u,
  "app: unit tests": /package's tests: [\d,]+ \(([\d,]+) units/u,
  "app: server tests": /units, ([\d,]+) server/u,
  "app: change-log tests": /server, ([\d,]+) change log\)/u,
  "Chromium tests": /Chromium: ([\d,]+) tests/u,
  "starter: tests": /starter's: ([\d,]+) tests/u,
};
// --write: the report's figures set to the files' (then --check passes).
if (process.argv.includes("--write")) {
  let text = report;
  const fmt = n => n.toLocaleString("en-US");
  for (const [name, pattern] of Object.entries(said)) {
    const body = text.slice(start, text.indexOf("\n\n**", start));
    const flat = new RegExp(pattern.source.replace(/ /gu, "\\s+"), "u");
    const m = flat.exec(body);
    if (!m) continue;
    const at = start + m.index + m[0].lastIndexOf(m[1]);
    text = text.slice(0, at) + fmt(figures[name]) + text.slice(at + m[1].length);
  }
  writeFileSync(join(root, "reports/06-perseus-starter.md"), text);
  console.log("sizes --write: the report's figures set.");
  process.exit(0);
}
const wrong = [];
// The package's version: in the paragraph, and every "studio.N" of the
// report's header (before § 1) is this one.
const studio = /studio\.\d+$/u.exec(appVersion)?.[0];
if (!block.includes(`package is ${appVersion}`)) wrong.push(`app: version: the paragraph does not say "package is ${appVersion}"`);
const header = report.slice(0, report.indexOf("\n## 1."));
for (const m of header.matchAll(/studio\.\d+/gu)) if (studio && m[0] !== studio) wrong.push(`the header says ${m[0]}, the package is ${appVersion}`);
for (const [name, pattern] of Object.entries(said)) {
  const found = pattern.exec(block)?.[1];
  if (found === undefined) wrong.push(`${name}: not found in the report's paragraph`);
  else if (number(found) !== figures[name]) wrong.push(`${name}: the report says ${found}, it is ${figures[name]}`);
}
if (wrong.length > 0) {
  console.error(`sizes --check: reports/06-perseus-starter.md §5 is stale —\n  ${wrong.join("\n  ")}\n(node lab/starter-bench/sizes.mjs gives every figure)`);
  process.exit(1);
}
console.log("sizes --check: the report's figures are the files'.");
