import { open } from "./lib.mjs";
const { browser, page, origin } = await open(13100, "camille", { locale: "en" });
await page.goto(origin + "/chest/candidates/7");
await page.getByRole("button", { name: "Interview", exact: true }).click();
await page.locator("dialog[open]").getByText("I choose the time").click();
const day = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Paris" }).format(new Date(Date.now() + 2 * 86400000));
await page.locator("#iv-day").fill(day);
await page.locator("#iv-day").press("Tab");
await page.locator("dialog[open] .check", { hasText: "Hugo Bernard" }).locator("input").check();
await page.waitForTimeout(1500);
const t = await page.locator("dialog[open]").innerText();
console.log(t.slice(t.indexOf("Length")));
console.log(await page.locator("dialog[open] .check input").evaluateAll(e => e.map(x => x.checked)));
await browser.close();
